services:
  redis:
    image: redis:7-alpine
    container_name: datamingle-redis
    restart: always
    command: redis-server --requirepass 123456
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  mysql:
    image: mysql:8.0
    container_name: datamingle-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/my.cnf:/etc/mysql/my.cnf"
      - "./mysql/datadir:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: archery
      MYSQL_ROOT_PASSWORD: 123456
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 20

  goinception:
    image: hanchuanchuan/goinception
    platform: linux/amd64
    container_name: datamingle-goinception
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - "./inception/config.toml:/etc/config.toml"

  archery:
    image: datamingle-archery:local-arm
    container_name: datamingle-archery
    restart: always
    build:
      context: ../..
      dockerfile: src/docker/Dockerfile.local-arm
    depends_on:
      redis:
        condition: service_healthy
      mysql:
        condition: service_healthy
      goinception:
        condition: service_started
    ports:
      - "9123:9123"
    volumes:
      - "./archery/settings.py:/opt/archery/local_settings.py"
      - "./archery/soar.yaml:/etc/soar.yaml"
      - "./archery/docs.md:/opt/archery/docs/docs.md"
      - "./archery/downloads:/opt/archery/downloads"
      - "../../sql/migrations:/opt/archery/sql/migrations"
      - "./archery/logs:/opt/archery/logs"
      - "./archery/keys:/opt/archery/keys"
    environment:
      RUN_MIGRATIONS_ON_START: "1"
    entrypoint: "bash /opt/archery/src/docker/startup.sh"
    env_file:
      - .env.local-arm
