name: 🐛 Bug Report
description: Please use this template for bug reports. Incomplete submissions may be closed.
title: "Briefly describe the issue"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue. Before submitting, please check the [Wiki](https://github.com/jruszo/Datamingle/wiki) and [FAQ](https://github.com/jruszo/Datamingle/wiki/FAQ) to confirm this is a bug that needs a fix. For usage questions or ideas/suggestions, please post in [Discussions](https://github.com/jruszo/Datamingle/discussions). Thanks again for contributing to Datamingle.
  - type: textarea
    id: what-happened
    attributes:
      label: Reproduction Steps
      description: Describe what happened, where it happened, and how to reproduce it.
      placeholder: |
        1. Open the refrigerator door
        2. Put the elephant inside
        3. Close the refrigerator door
    validations:
      required: true
  - type: textarea
    id: current-behavior
    attributes:
      label: Unexpected Result
      description: |
        Describe the error you encountered. If possible, include screenshots.

        Tip: You can drag and drop files to attach images. Please make sure sensitive information is removed.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Paste related log output here. It will be auto-formatted. Common log locations:
        1. logs/archery.log
        2. logs/qcluster.log
        3. docker logs archery -f --tail=10
      render: shell
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: Tell us which Datamingle version you are using.
      placeholder: 1.9.1
    validations:
      required: true
  - type: dropdown
    id: deploy
    attributes:
      label: Deployment Method
      description: Tell us how your application is deployed.
      options:
        - Docker
        - K8S
        - Manual Deployment
    validations:
      required: true
  - type: textarea
    id: other-msg
    attributes:
      label: Additional context (for example database version)
      description: |
        Some details can be collected from the Datamingle debug API: [Example debug endpoint](https://demo.archerydms.com/api/debug?full=true)
        - **MySQL**: 5.7.26
        - **Browser**: Chrome
        - **goInception**: v1.2.5-49
    validations:
      required: false
