blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/jruszo/Datamingle/discussions
    about: Please use Discussions for non-bug questions and general conversation.
