# Generated by Django 6.0.3 on 2026-05-13 17:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sql", "0017_alter_taskschedule_backend"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("disabled", "Disabled"),
                            ("revoked", "Revoked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "workos_api_key_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "api_key_prefix",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("hostname", models.CharField(blank=True, default="", max_length=255)),
                ("platform", models.CharField(blank=True, default="", max_length=64)),
                (
                    "architecture",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "agent_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "install_id",
                    models.CharField(
                        blank=True, default=None, max_length=80, null=True, unique=True
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_disconnected_at", models.DateTimeField(blank=True, null=True)),
                ("last_config_revision", models.PositiveIntegerField(default=0)),
                ("desired_config_revision", models.PositiveIntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agent",
                "ordering": ("name",),
                "permissions": (("menu_agent", "Can access Agents menu"),),
            },
        ),
        migrations.CreateModel(
            name="AgentCommand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workflow_type", models.CharField(max_length=64)),
                ("workflow_id", models.CharField(max_length=128)),
                (
                    "command_type",
                    models.CharField(
                        choices=[
                            ("query.execute", "Query Execute"),
                            ("schema.change", "Schema Change"),
                            ("connection.test", "Connection Test"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("dispatched", "Dispatched"),
                            ("accepted", "Accepted"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.JSONField(blank=True, default=dict)),
                (
                    "lease_owner",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_requested_at", models.DateTimeField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="api_agents.agent",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_commands",
                        to="sql.instance",
                    ),
                ),
            ],
            options={
                "db_table": "agent_command",
                "ordering": ("-create_time",),
            },
        ),
        migrations.CreateModel(
            name="AgentCommandEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=64)),
                ("message", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="api_agents.agentcommand",
                    ),
                ),
            ],
            options={
                "db_table": "agent_command_event",
                "ordering": ("create_time", "id"),
            },
        ),
        migrations.CreateModel(
            name="AgentConfigRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                (
                    "config_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_revisions",
                        to="api_agents.agent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agent_config_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "agent_config_revision",
                "ordering": ("-revision",),
            },
        ),
        migrations.CreateModel(
            name="AgentInstanceAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("modules", models.JSONField(blank=True, default=list)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("command_enabled", models.BooleanField(default=False)),
                ("metrics_enabled", models.BooleanField(default=True)),
                ("online_schema_enabled", models.BooleanField(default=False)),
                ("logs_enabled", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="api_agents.agent",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_assignments",
                        to="sql.instance",
                    ),
                ),
            ],
            options={
                "db_table": "agent_instance_assignment",
                "ordering": ("agent_id", "instance_id"),
            },
        ),
        migrations.CreateModel(
            name="AgentToolArtifact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tool_name",
                    models.CharField(
                        choices=[
                            ("gh-ost", "gh-ost"),
                            ("pt-online-schema-change", "pt-online-schema-change"),
                        ],
                        max_length=64,
                    ),
                ),
                ("version", models.CharField(max_length=64)),
                ("platform", models.CharField(max_length=64)),
                ("architecture", models.CharField(max_length=64)),
                ("download_url", models.URLField(max_length=1024)),
                ("sha256", models.CharField(blank=True, default="", max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("enabled", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "agent_tool_artifact",
                "ordering": ("tool_name", "version", "platform", "architecture"),
                "unique_together": {
                    ("tool_name", "version", "platform", "architecture")
                },
            },
        ),
        migrations.AddIndex(
            model_name="agentcommand",
            index=models.Index(
                fields=["agent", "status"], name="agent_comma_agent_i_c8321a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agentcommand",
            index=models.Index(
                fields=["instance", "status"], name="agent_comma_instanc_771aed_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="agentconfigrevision",
            unique_together={("agent", "revision")},
        ),
        migrations.AlterUniqueTogether(
            name="agentinstanceassignment",
            unique_together={("agent", "instance")},
        ),
    ]
