# Generated by Django 6.0.3 on 2026-05-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="api_key_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
