# Generated by Django 6.0.3 on 2026-05-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0002_agent_api_key_hash"),
        ("sql", "0017_alter_taskschedule_backend"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="api_key_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default=None,
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="agentcommand",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("idempotency_key",),
                name="unique_agent_command_idempotency_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="agentinstanceassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("command_enabled", True), ("enabled", True)),
                fields=("instance",),
                name="unique_active_command_assignment_per_instance",
            ),
        ),
    ]
