# Generated by Django 6.0.3 on 2026-05-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0003_alter_agent_api_key_hash_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="agentcommand",
            name="unique_agent_command_idempotency_key",
        ),
        migrations.RemoveConstraint(
            model_name="agentinstanceassignment",
            name="unique_active_command_assignment_per_instance",
        ),
        migrations.AddField(
            model_name="agentinstanceassignment",
            name="active_command_instance_id",
            field=models.PositiveIntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="idempotency_key",
            field=models.CharField(
                blank=True, default=None, max_length=128, null=True, unique=True
            ),
        ),
    ]
