# Generated by Django 6.0.3 on 2026-05-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_agents",
            "0004_remove_agentcommand_unique_agent_command_idempotency_key_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentcommand",
            name="idempotency_key",
            field=models.CharField(blank=True, default="", max_length=128, unique=True),
        ),
    ]
