# Generated by Django 6.0.3 on 2026-05-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0005_alter_agentcommand_idempotency_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentcommand",
            name="idempotency_key",
            field=models.CharField(
                blank=True, default=None, max_length=128, null=True, unique=True
            ),
        ),
    ]
