# Generated by Django 6.0.3 on 2026-05-15 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0006_alter_agentcommand_idempotency_key"),
        ("sql", "0018_instance_execution_mode_infrastructurenode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="node",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="sql.infrastructurenode",
            ),
        ),
        migrations.AddField(
            model_name="agentcommand",
            name="node",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_commands",
                to="sql.infrastructurenode",
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("query.execute", "Query Execute"),
                    ("schema.change", "Schema Change"),
                    ("connection.test", "Connection Test"),
                    ("service.discovery", "Service Discovery"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_commands",
                to="sql.instance",
            ),
        ),
    ]
