# Generated by Django 6.0.3 on 2026-05-22 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0007_agent_local_node_agentnodeassignment_and_more"),
        ("sql", "0020_infrastructurenode_instance_node"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinstanceassignment",
            name="local_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_agent_instance_assignments",
                to="sql.infrastructurenode",
            ),
        ),
    ]
