# Generated by Codex on 2026-05-14

from django.db import migrations


def attach_agents_to_nodes(apps, schema_editor):
    Agent = apps.get_model("api_agents", "Agent")
    AgentInstanceAssignment = apps.get_model("api_agents", "AgentInstanceAssignment")
    db_alias = schema_editor.connection.alias

    for agent in Agent.objects.using(db_alias).filter(node__isnull=True).order_by("id"):
        node_ids = list(
            AgentInstanceAssignment.objects.using(db_alias)
            .filter(agent_id=agent.id, instance__node__isnull=False)
            .values_list("instance__node_id", flat=True)
            .distinct()
            .order_by("instance__node_id")
        )
        if not node_ids:
            continue
        agent.node_id = node_ids[0]
        agent.save(update_fields=["node"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0019_group_existing_instances_into_nodes"),
        ("api_agents", "0007_agent_node_agentcommand_node_and_more"),
    ]

    operations = [
        migrations.RunPython(attach_agents_to_nodes, noop_reverse),
    ]
