# Generated by Django 6.0.3 on 2026-05-26 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0008_attach_existing_agents_to_nodes"),
        ("sql", "0020_merge_20260526_2116"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agent",
            name="node",
        ),
        migrations.RemoveField(
            model_name="agentcommand",
            name="node",
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("query.execute", "Query Execute"),
                    ("schema.change", "Schema Change"),
                    ("connection.test", "Connection Test"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="agentcommand",
            name="instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent_commands",
                to="sql.instance",
            ),
        ),
    ]
