# Generated by Django 6.0.3 on 2026-05-27 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0010_alter_agentcommand_command_type"),
        ("sql", "0022_infrastructurenode_instance_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="local_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="local_agents",
                to="sql.infrastructurenode",
            ),
        ),
        migrations.AddField(
            model_name="agentinstanceassignment",
            name="local_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="local_agent_instance_assignments",
                to="sql.infrastructurenode",
            ),
        ),
        migrations.CreateModel(
            name="AgentNodeAssignment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("modules", models.JSONField(blank=True, default=list)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                ("command_enabled", models.BooleanField(default=False)),
                (
                    "active_command_node_id",
                    models.PositiveIntegerField(
                        blank=True, editable=False, null=True, unique=True
                    ),
                ),
                ("metrics_enabled", models.BooleanField(default=True)),
                ("online_schema_enabled", models.BooleanField(default=False)),
                ("logs_enabled", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_assignments",
                        to="api_agents.agent",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_assignments",
                        to="sql.infrastructurenode",
                    ),
                ),
            ],
            options={
                "db_table": "agent_node_assignment",
                "ordering": ("agent_id", "node_id"),
                "unique_together": {("agent", "node")},
            },
        ),
        migrations.AddField(
            model_name="agentinstanceassignment",
            name="node_assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instance_assignments",
                to="api_agents.agentnodeassignment",
            ),
        ),
    ]
