# Generated by Django 6.0.3 on 2026-06-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_agents",
            "0011_agent_local_node_agentinstanceassignment_local_node_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="last_websocket_pong_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
