# Generated by Django 6.0.3 on 2026-06-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0012_agent_last_websocket_pong_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttoolartifact",
            name="tool_name",
            field=models.CharField(
                choices=[
                    ("gh-ost", "gh-ost"),
                    ("pt-online-schema-change", "pt-online-schema-change"),
                    ("node_exporter", "node_exporter"),
                ],
                max_length=64,
            ),
        ),
    ]
