# Generated by Django 6.0.3 on 2026-06-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0013_alter_agenttoolartifact_tool_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttoolartifact",
            name="tool_name",
            field=models.CharField(
                choices=[
                    ("gh-ost", "gh-ost"),
                    ("pt-online-schema-change", "pt-online-schema-change"),
                    ("node_exporter", "node_exporter"),
                    ("mysqld_exporter", "mysqld_exporter"),
                    ("postgres_exporter", "postgres_exporter"),
                ],
                max_length=64,
            ),
        ),
    ]
