# Generated by Django 6.0.3 on 2026-07-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0016_alter_agenttoolartifact_tool_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentcommand",
            name="command_type",
            field=models.CharField(
                choices=[
                    ("query.execute", "Query Execute"),
                    ("schema.change", "Schema Change"),
                    ("connection.test", "Connection Test"),
                    ("inventory.collect", "Inventory Collect"),
                    ("workflow.check", "Workflow Check"),
                    ("workflow.execute", "Workflow Execute"),
                    ("export.check", "Export Check"),
                    ("export.execute", "Export Execute"),
                    ("archive.execute", "Archive Execute"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
