# Generated by Django 4.1.13 on 2026-03-06 22:55

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mirage.fields
import sql.models
import sql.plugins.password


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlowQuery",
            fields=[
                (
                    "checksum",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("fingerprint", models.TextField()),
                ("sample", models.TextField()),
                ("first_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "last_seen",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("reviewed_by", models.CharField(blank=True, max_length=20, null=True)),
                ("reviewed_on", models.DateTimeField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Slow Query Statistics",
                "verbose_name_plural": "Slow Query Statistics",
                "db_table": "mysql_slow_query_review",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SlowQueryHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname_max", models.CharField(max_length=64)),
                ("client_max", models.CharField(max_length=64, null=True)),
                ("user_max", models.CharField(max_length=64)),
                ("db_max", models.CharField(default=None, max_length=64, null=True)),
                ("bytes_max", models.CharField(max_length=64, null=True)),
                ("sample", models.TextField()),
                ("ts_min", models.DateTimeField(db_index=True)),
                ("ts_max", models.DateTimeField()),
                ("ts_cnt", models.FloatField(blank=True, null=True)),
                (
                    "query_time_sum",
                    models.FloatField(
                        blank=True, db_column="Query_time_sum", null=True
                    ),
                ),
                (
                    "query_time_min",
                    models.FloatField(
                        blank=True, db_column="Query_time_min", null=True
                    ),
                ),
                (
                    "query_time_max",
                    models.FloatField(
                        blank=True, db_column="Query_time_max", null=True
                    ),
                ),
                (
                    "query_time_pct_95",
                    models.FloatField(
                        blank=True, db_column="Query_time_pct_95", null=True
                    ),
                ),
                (
                    "query_time_stddev",
                    models.FloatField(
                        blank=True, db_column="Query_time_stddev", null=True
                    ),
                ),
                (
                    "query_time_median",
                    models.FloatField(
                        blank=True, db_column="Query_time_median", null=True
                    ),
                ),
                (
                    "lock_time_sum",
                    models.FloatField(blank=True, db_column="Lock_time_sum", null=True),
                ),
                (
                    "lock_time_min",
                    models.FloatField(blank=True, db_column="Lock_time_min", null=True),
                ),
                (
                    "lock_time_max",
                    models.FloatField(blank=True, db_column="Lock_time_max", null=True),
                ),
                (
                    "lock_time_pct_95",
                    models.FloatField(
                        blank=True, db_column="Lock_time_pct_95", null=True
                    ),
                ),
                (
                    "lock_time_stddev",
                    models.FloatField(
                        blank=True, db_column="Lock_time_stddev", null=True
                    ),
                ),
                (
                    "lock_time_median",
                    models.FloatField(
                        blank=True, db_column="Lock_time_median", null=True
                    ),
                ),
                (
                    "rows_sent_sum",
                    models.FloatField(blank=True, db_column="Rows_sent_sum", null=True),
                ),
                (
                    "rows_sent_min",
                    models.FloatField(blank=True, db_column="Rows_sent_min", null=True),
                ),
                (
                    "rows_sent_max",
                    models.FloatField(blank=True, db_column="Rows_sent_max", null=True),
                ),
                (
                    "rows_sent_pct_95",
                    models.FloatField(
                        blank=True, db_column="Rows_sent_pct_95", null=True
                    ),
                ),
                (
                    "rows_sent_stddev",
                    models.FloatField(
                        blank=True, db_column="Rows_sent_stddev", null=True
                    ),
                ),
                (
                    "rows_sent_median",
                    models.FloatField(
                        blank=True, db_column="Rows_sent_median", null=True
                    ),
                ),
                (
                    "rows_examined_sum",
                    models.FloatField(
                        blank=True, db_column="Rows_examined_sum", null=True
                    ),
                ),
                (
                    "rows_examined_min",
                    models.FloatField(
                        blank=True, db_column="Rows_examined_min", null=True
                    ),
                ),
                (
                    "rows_examined_max",
                    models.FloatField(
                        blank=True, db_column="Rows_examined_max", null=True
                    ),
                ),
                (
                    "rows_examined_pct_95",
                    models.FloatField(
                        blank=True, db_column="Rows_examined_pct_95", null=True
                    ),
                ),
                (
                    "rows_examined_stddev",
                    models.FloatField(
                        blank=True, db_column="Rows_examined_stddev", null=True
                    ),
                ),
                (
                    "rows_examined_median",
                    models.FloatField(
                        blank=True, db_column="Rows_examined_median", null=True
                    ),
                ),
                (
                    "rows_affected_sum",
                    models.FloatField(
                        blank=True, db_column="Rows_affected_sum", null=True
                    ),
                ),
                (
                    "rows_affected_min",
                    models.FloatField(
                        blank=True, db_column="Rows_affected_min", null=True
                    ),
                ),
                (
                    "rows_affected_max",
                    models.FloatField(
                        blank=True, db_column="Rows_affected_max", null=True
                    ),
                ),
                (
                    "rows_affected_pct_95",
                    models.FloatField(
                        blank=True, db_column="Rows_affected_pct_95", null=True
                    ),
                ),
                (
                    "rows_affected_stddev",
                    models.FloatField(
                        blank=True, db_column="Rows_affected_stddev", null=True
                    ),
                ),
                (
                    "rows_affected_median",
                    models.FloatField(
                        blank=True, db_column="Rows_affected_median", null=True
                    ),
                ),
                (
                    "rows_read_sum",
                    models.FloatField(blank=True, db_column="Rows_read_sum", null=True),
                ),
                (
                    "rows_read_min",
                    models.FloatField(blank=True, db_column="Rows_read_min", null=True),
                ),
                (
                    "rows_read_max",
                    models.FloatField(blank=True, db_column="Rows_read_max", null=True),
                ),
                (
                    "rows_read_pct_95",
                    models.FloatField(
                        blank=True, db_column="Rows_read_pct_95", null=True
                    ),
                ),
                (
                    "rows_read_stddev",
                    models.FloatField(
                        blank=True, db_column="Rows_read_stddev", null=True
                    ),
                ),
                (
                    "rows_read_median",
                    models.FloatField(
                        blank=True, db_column="Rows_read_median", null=True
                    ),
                ),
                (
                    "merge_passes_sum",
                    models.FloatField(
                        blank=True, db_column="Merge_passes_sum", null=True
                    ),
                ),
                (
                    "merge_passes_min",
                    models.FloatField(
                        blank=True, db_column="Merge_passes_min", null=True
                    ),
                ),
                (
                    "merge_passes_max",
                    models.FloatField(
                        blank=True, db_column="Merge_passes_max", null=True
                    ),
                ),
                (
                    "merge_passes_pct_95",
                    models.FloatField(
                        blank=True, db_column="Merge_passes_pct_95", null=True
                    ),
                ),
                (
                    "merge_passes_stddev",
                    models.FloatField(
                        blank=True, db_column="Merge_passes_stddev", null=True
                    ),
                ),
                (
                    "merge_passes_median",
                    models.FloatField(
                        blank=True, db_column="Merge_passes_median", null=True
                    ),
                ),
                (
                    "innodb_io_r_ops_min",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_ops_min", null=True
                    ),
                ),
                (
                    "innodb_io_r_ops_max",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_ops_max", null=True
                    ),
                ),
                (
                    "innodb_io_r_ops_pct_95",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_ops_pct_95", null=True
                    ),
                ),
                (
                    "innodb_io_r_ops_stddev",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_ops_stddev", null=True
                    ),
                ),
                (
                    "innodb_io_r_ops_median",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_ops_median", null=True
                    ),
                ),
                (
                    "innodb_io_r_bytes_min",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_bytes_min", null=True
                    ),
                ),
                (
                    "innodb_io_r_bytes_max",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_bytes_max", null=True
                    ),
                ),
                (
                    "innodb_io_r_bytes_pct_95",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_bytes_pct_95", null=True
                    ),
                ),
                (
                    "innodb_io_r_bytes_stddev",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_bytes_stddev", null=True
                    ),
                ),
                (
                    "innodb_io_r_bytes_median",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_bytes_median", null=True
                    ),
                ),
                (
                    "innodb_io_r_wait_min",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_wait_min", null=True
                    ),
                ),
                (
                    "innodb_io_r_wait_max",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_wait_max", null=True
                    ),
                ),
                (
                    "innodb_io_r_wait_pct_95",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_wait_pct_95", null=True
                    ),
                ),
                (
                    "innodb_io_r_wait_stddev",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_wait_stddev", null=True
                    ),
                ),
                (
                    "innodb_io_r_wait_median",
                    models.FloatField(
                        blank=True, db_column="InnoDB_IO_r_wait_median", null=True
                    ),
                ),
                (
                    "innodb_rec_lock_wait_min",
                    models.FloatField(
                        blank=True, db_column="InnoDB_rec_lock_wait_min", null=True
                    ),
                ),
                (
                    "innodb_rec_lock_wait_max",
                    models.FloatField(
                        blank=True, db_column="InnoDB_rec_lock_wait_max", null=True
                    ),
                ),
                (
                    "innodb_rec_lock_wait_pct_95",
                    models.FloatField(
                        blank=True, db_column="InnoDB_rec_lock_wait_pct_95", null=True
                    ),
                ),
                (
                    "innodb_rec_lock_wait_stddev",
                    models.FloatField(
                        blank=True, db_column="InnoDB_rec_lock_wait_stddev", null=True
                    ),
                ),
                (
                    "innodb_rec_lock_wait_median",
                    models.FloatField(
                        blank=True, db_column="InnoDB_rec_lock_wait_median", null=True
                    ),
                ),
                (
                    "innodb_queue_wait_min",
                    models.FloatField(
                        blank=True, db_column="InnoDB_queue_wait_min", null=True
                    ),
                ),
                (
                    "innodb_queue_wait_max",
                    models.FloatField(
                        blank=True, db_column="InnoDB_queue_wait_max", null=True
                    ),
                ),
                (
                    "innodb_queue_wait_pct_95",
                    models.FloatField(
                        blank=True, db_column="InnoDB_queue_wait_pct_95", null=True
                    ),
                ),
                (
                    "innodb_queue_wait_stddev",
                    models.FloatField(
                        blank=True, db_column="InnoDB_queue_wait_stddev", null=True
                    ),
                ),
                (
                    "innodb_queue_wait_median",
                    models.FloatField(
                        blank=True, db_column="InnoDB_queue_wait_median", null=True
                    ),
                ),
                (
                    "innodb_pages_distinct_min",
                    models.FloatField(
                        blank=True, db_column="InnoDB_pages_distinct_min", null=True
                    ),
                ),
                (
                    "innodb_pages_distinct_max",
                    models.FloatField(
                        blank=True, db_column="InnoDB_pages_distinct_max", null=True
                    ),
                ),
                (
                    "innodb_pages_distinct_pct_95",
                    models.FloatField(
                        blank=True, db_column="InnoDB_pages_distinct_pct_95", null=True
                    ),
                ),
                (
                    "innodb_pages_distinct_stddev",
                    models.FloatField(
                        blank=True, db_column="InnoDB_pages_distinct_stddev", null=True
                    ),
                ),
                (
                    "innodb_pages_distinct_median",
                    models.FloatField(
                        blank=True, db_column="InnoDB_pages_distinct_median", null=True
                    ),
                ),
                (
                    "qc_hit_cnt",
                    models.FloatField(blank=True, db_column="QC_Hit_cnt", null=True),
                ),
                (
                    "qc_hit_sum",
                    models.FloatField(blank=True, db_column="QC_Hit_sum", null=True),
                ),
                (
                    "full_scan_cnt",
                    models.FloatField(blank=True, db_column="Full_scan_cnt", null=True),
                ),
                (
                    "full_scan_sum",
                    models.FloatField(blank=True, db_column="Full_scan_sum", null=True),
                ),
                (
                    "full_join_cnt",
                    models.FloatField(blank=True, db_column="Full_join_cnt", null=True),
                ),
                (
                    "full_join_sum",
                    models.FloatField(blank=True, db_column="Full_join_sum", null=True),
                ),
                (
                    "tmp_table_cnt",
                    models.FloatField(blank=True, db_column="Tmp_table_cnt", null=True),
                ),
                (
                    "tmp_table_sum",
                    models.FloatField(blank=True, db_column="Tmp_table_sum", null=True),
                ),
                (
                    "tmp_table_on_disk_cnt",
                    models.FloatField(
                        blank=True, db_column="Tmp_table_on_disk_cnt", null=True
                    ),
                ),
                (
                    "tmp_table_on_disk_sum",
                    models.FloatField(
                        blank=True, db_column="Tmp_table_on_disk_sum", null=True
                    ),
                ),
                (
                    "filesort_cnt",
                    models.FloatField(blank=True, db_column="Filesort_cnt", null=True),
                ),
                (
                    "filesort_sum",
                    models.FloatField(blank=True, db_column="Filesort_sum", null=True),
                ),
                (
                    "filesort_on_disk_cnt",
                    models.FloatField(
                        blank=True, db_column="Filesort_on_disk_cnt", null=True
                    ),
                ),
                (
                    "filesort_on_disk_sum",
                    models.FloatField(
                        blank=True, db_column="Filesort_on_disk_sum", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Slow Query Detail",
                "verbose_name_plural": "Slow Query Detail",
                "db_table": "mysql_slow_query_review_history",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ArchiveConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=50, verbose_name="Archive Configuration Title"
                    ),
                ),
                (
                    "audit_auth_groups",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Audit Authorization Groups",
                    ),
                ),
                (
                    "src_db_name",
                    models.CharField(max_length=64, verbose_name="Source Database"),
                ),
                (
                    "src_table_name",
                    models.CharField(max_length=64, verbose_name="Source Table"),
                ),
                (
                    "dest_db_name",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Destination Database",
                    ),
                ),
                (
                    "dest_table_name",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="Destination Table",
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        max_length=1000, verbose_name="Archive Condition (WHERE clause)"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("dest", "Other Instance"),
                            ("purge", "Direct Delete"),
                        ],
                        max_length=10,
                        verbose_name="Archive Mode",
                    ),
                ),
                ("no_delete", models.BooleanField(verbose_name="Retain Source Data")),
                (
                    "sleep",
                    models.IntegerField(
                        default=1, verbose_name="Sleep Seconds After Each Limited Batch"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Pending review"),
                            (1, "Approved"),
                            (2, "Rejected"),
                            (3, "Canceled"),
                        ],
                        default=1,
                        verbose_name="Audit Status",
                    ),
                ),
                (
                    "state",
                    models.BooleanField(default=True, verbose_name="Archive Enabled"),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Requester"
                    ),
                ),
                (
                    "user_display",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Requester Display Name",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "last_archive_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Archive Time"
                    ),
                ),
                (
                    "sys_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="System Modified Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Archive Configuration",
                "verbose_name_plural": "Archive Configuration",
                "db_table": "archive_config",
                "managed": True,
            },
            bases=(models.Model, sql.models.WorkflowAuditMixin),
        ),
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="User ID")),
                (
                    "user_name",
                    models.CharField(max_length=30, null=True, verbose_name="Username"),
                ),
                (
                    "user_display",
                    models.CharField(
                        max_length=50, null=True, verbose_name="User Display Name"
                    ),
                ),
                ("action", models.CharField(max_length=255, verbose_name="Action")),
                (
                    "extra_info",
                    models.TextField(null=True, verbose_name="Additional Info"),
                ),
                (
                    "action_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Action Time"),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Log",
                "db_table": "audit_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="CloudAccessKey",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("aliyun", "aliyun")], default="", max_length=20
                    ),
                ),
                ("key_id", models.CharField(max_length=200)),
                ("key_secret", models.CharField(max_length=200)),
                ("remark", models.CharField(blank=True, default="", max_length=50)),
            ],
            options={
                "verbose_name": "Cloud Credential Configuration",
                "verbose_name_plural": "Cloud Credential Configuration",
                "db_table": "cloud_access_key",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Config Item"
                    ),
                ),
                (
                    "value",
                    mirage.fields.EncryptedCharField(
                        max_length=500, verbose_name="Config Value"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
                "db_table": "sql_config",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DataMaskingRules",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.IntegerField(
                        choices=[
                            (1, "Phone Number"),
                            (2, "ID Number"),
                            (3, "Bank Card"),
                            (4, "Email"),
                            (5, "Amount"),
                            (6, "Other"),
                            (100, "Three-Segment Generic Masking Rule"),
                        ],
                        unique=True,
                        verbose_name="Rule Type",
                    ),
                ),
                (
                    "rule_regex",
                    models.CharField(
                        max_length=255,
                        verbose_name="Masking regex. Expression must have groups; masked group is replaced by ****.",
                    ),
                ),
                ("hide_group", models.IntegerField(verbose_name="Group To Hide")),
                (
                    "rule_desc",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Rule Description",
                    ),
                ),
                ("sys_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Data Masking Rule Configuration",
                "verbose_name_plural": "Data Masking Rule Configuration",
                "db_table": "data_masking_rules",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Instance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Instance Name"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("master", "Primary"), ("slave", "Replica")],
                        max_length=6,
                        verbose_name="Instance Type",
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("mssql", "MsSQL"),
                            ("redis", "Redis"),
                            ("pgsql", "PgSQL"),
                            ("oracle", "Oracle"),
                            ("mongo", "Mongo"),
                            ("phoenix", "Phoenix"),
                            ("odps", "ODPS"),
                            ("clickhouse", "ClickHouse"),
                            ("goinception", "goInception"),
                            ("cassandra", "Cassandra"),
                            ("doris", "Doris"),
                            ("elasticsearch", "Elasticsearch"),
                            ("opensearch", "OpenSearch"),
                            ("memcached", "Memcached"),
                        ],
                        max_length=20,
                        verbose_name="Database Type",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[("standalone", "Standalone"), ("cluster", "Cluster")],
                        default="",
                        max_length=10,
                        verbose_name="Run Mode",
                    ),
                ),
                (
                    "host",
                    models.CharField(max_length=200, verbose_name="Instance Host"),
                ),
                ("port", models.IntegerField(default=0, verbose_name="Port")),
                (
                    "user",
                    mirage.fields.EncryptedCharField(
                        blank=True, default="", max_length=200, verbose_name="Username"
                    ),
                ),
                (
                    "password",
                    mirage.fields.EncryptedCharField(
                        blank=True, default="", max_length=300, verbose_name="Password"
                    ),
                ),
                (
                    "is_ssl",
                    models.BooleanField(default=False, verbose_name="Enable SSL"),
                ),
                (
                    "verify_ssl",
                    models.BooleanField(
                        default=True, verbose_name="Verify Server SSL Certificate"
                    ),
                ),
                (
                    "db_name",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Database"
                    ),
                ),
                (
                    "show_db_name_regex",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Regex expression. Example: ^(test_db|dmp_db|za.*)$. Redis example: ^(0|4|6|11|12|13)$",
                        max_length=1024,
                        verbose_name="Visible Database Regex",
                    ),
                ),
                (
                    "denied_db_name_regex",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Regex expression. Hidden rules override visible rules.",
                        max_length=1024,
                        verbose_name="Hidden Database Regex",
                    ),
                ),
                (
                    "charset",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Charset"
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Oracle service name",
                    ),
                ),
                (
                    "sid",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Oracle sid"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
            ],
            options={
                "verbose_name": "Instance Configuration",
                "verbose_name_plural": "Instance Configuration",
                "db_table": "sql_instance",
                "managed": True,
            },
            bases=(models.Model, sql.plugins.password.DummyMixin),
        ),
        migrations.CreateModel(
            name="InstanceTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tag_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Tag Code"
                    ),
                ),
                (
                    "tag_name",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Tag Name"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Active Status"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Tag",
                "verbose_name_plural": "Instance Tag",
                "db_table": "sql_instance_tag",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("menu_dashboard", "Menu Dashboard"),
                    ("menu_sqlcheck", "Menu SQL Review"),
                    ("menu_sqlworkflow", "Menu SQL Deployment"),
                    ("menu_sqlanalyze", "Menu SQL Analysis"),
                    ("menu_query", "Menu SQL Query"),
                    ("menu_sqlquery", "Menu Online Query"),
                    ("menu_queryapplylist", "Menu Privilege Management"),
                    ("menu_sqloptimize", "Menu SQL Optimization"),
                    ("menu_sqladvisor", "Menu Optimization Tools"),
                    ("menu_slowquery", "Menu Slow Query Log"),
                    ("menu_instance", "Menu Instance Management"),
                    ("menu_instance_list", "Menu Instance List"),
                    ("menu_dbdiagnostic", "Menu Session Management"),
                    ("menu_database", "Menu Database Management"),
                    ("menu_instance_account", "Menu Instance Account Management"),
                    ("menu_param", "Menu Parameter Configuration"),
                    ("menu_data_dictionary", "Menu Data Dictionary"),
                    ("menu_tools", "Menu Tool Plugins"),
                    ("menu_archive", "Menu Data Archive"),
                    ("menu_my2sql", "Menu My2SQL"),
                    ("menu_schemasync", "Menu SchemaSync"),
                    ("menu_system", "Menu System Management"),
                    ("menu_document", "Menu Related Documentation"),
                    ("menu_openapi", "Menu OpenAPI"),
                    ("sql_submit", "Submit SQL Deployment Workflow"),
                    ("sql_review", "Review SQL Deployment Workflow"),
                    (
                        "sql_execute_for_resource_group",
                        "Execute SQL Deployment Workflow (Resource Group Scope)",
                    ),
                    (
                        "sql_execute",
                        "Execute SQL Deployment Workflow (Own Submissions Only)",
                    ),
                    ("sql_analyze", "Execute SQL Analysis"),
                    ("optimize_sqladvisor", "Execute SQLAdvisor"),
                    ("optimize_sqltuning", "Execute SQLTuning"),
                    ("optimize_soar", "Execute SOAR"),
                    ("query_applypriv", "Apply Query Privileges"),
                    ("query_mgtpriv", "Manage Query Privileges"),
                    ("query_review", "Review Query Privileges"),
                    ("query_submit", "Submit SQL Query"),
                    ("query_all_instances", "Query All Instances"),
                    (
                        "query_resource_group_instance",
                        "Query All Instances in Resource Group",
                    ),
                    ("process_view", "View Sessions"),
                    ("process_kill", "Kill Sessions"),
                    ("tablespace_view", "View Tablespaces"),
                    ("trx_view", "View Transaction Info"),
                    ("trxandlocks_view", "View Lock Info"),
                    ("instance_account_manage", "Manage Instance Accounts"),
                    ("param_view", "View Instance Parameters"),
                    ("param_edit", "Edit Instance Parameters"),
                    ("data_dictionary_export", "Export Data Dictionary"),
                    ("archive_apply", "Submit Archive Request"),
                    ("archive_review", "Review Archive Request"),
                    ("archive_mgt", "Manage Archive Request"),
                    ("audit_user", "Audit Permission"),
                    ("query_download", "Online Query Download Permission"),
                    ("offline_download", "Offline Download Permission"),
                    ("menu_sqlexportworkflow", "Menu Data Export"),
                    ("sqlexport_submit", "Submit Data Export"),
                ),
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instance_name",
                    models.CharField(max_length=50, verbose_name="Instance Name"),
                ),
                (
                    "db_name",
                    models.CharField(max_length=64, verbose_name="Database Name"),
                ),
                ("sqllog", models.TextField(verbose_name="Executed Query")),
                ("effect_row", models.BigIntegerField(verbose_name="Returned Rows")),
                (
                    "cost_time",
                    models.CharField(
                        default="", max_length=10, verbose_name="Execution Time"
                    ),
                ),
                ("username", models.CharField(max_length=30, verbose_name="Operator")),
                (
                    "user_display",
                    models.CharField(
                        default="", max_length=50, verbose_name="Operator Display Name"
                    ),
                ),
                (
                    "priv_check",
                    models.BooleanField(
                        choices=[(False, "Skipped"), (True, "Normal")],
                        default=False,
                        verbose_name="Privilege Check Status",
                    ),
                ),
                (
                    "hit_rule",
                    models.BooleanField(
                        choices=[(False, "Not Matched/Unknown"), (True, "Matched")],
                        default=False,
                        verbose_name="Masking Rule Matched",
                    ),
                ),
                (
                    "masking",
                    models.BooleanField(
                        choices=[(False, "No"), (True, "Yes")],
                        default=False,
                        verbose_name="Masking Applied Correctly",
                    ),
                ),
                (
                    "favorite",
                    models.BooleanField(
                        choices=[(False, "No"), (True, "Yes")],
                        default=False,
                        verbose_name="Favorite",
                    ),
                ),
                (
                    "alias",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Statement Alias",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Operation Time"
                    ),
                ),
                ("sys_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Query Log",
                "verbose_name_plural": "Query Log",
                "db_table": "query_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ResourceGroup",
            fields=[
                (
                    "group_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Group ID"
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Group Name"
                    ),
                ),
                (
                    "group_parent_id",
                    models.BigIntegerField(default=0, verbose_name="Parent ID"),
                ),
                (
                    "group_sort",
                    models.IntegerField(default=1, verbose_name="Sort Order"),
                ),
                ("group_level", models.IntegerField(default=1, verbose_name="Level")),
                (
                    "ding_webhook",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="DingTalk webhook URL"
                    ),
                ),
                (
                    "feishu_webhook",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Feishu webhook URL"
                    ),
                ),
                (
                    "qywx_webhook",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="WeCom webhook URL"
                    ),
                ),
                (
                    "is_deleted",
                    models.IntegerField(
                        choices=[(0, "No"), (1, "Yes")],
                        default=0,
                        verbose_name="Is Deleted",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("sys_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Resource Group Management",
                "verbose_name_plural": "Resource Group Management",
                "db_table": "resource_group",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SqlWorkflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow_name",
                    models.CharField(max_length=50, verbose_name="Workflow Name"),
                ),
                (
                    "demand_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Demand URL"
                    ),
                ),
                ("group_id", models.IntegerField(verbose_name="Group ID")),
                (
                    "group_name",
                    models.CharField(max_length=100, verbose_name="Group Name"),
                ),
                ("db_name", models.CharField(max_length=64, verbose_name="Database")),
                (
                    "syntax_type",
                    models.IntegerField(
                        choices=[
                            (0, "Other"),
                            (1, "DDL"),
                            (2, "DML"),
                            (3, "Offline Export"),
                        ],
                        default=0,
                        verbose_name="Workflow Type (0=Unknown, 1=DDL, 2=DML, 3=Offline Export)",
                    ),
                ),
                (
                    "is_backup",
                    models.BooleanField(
                        choices=[(False, "No"), (True, "Yes")],
                        default=True,
                        verbose_name="Backup Required",
                    ),
                ),
                ("engineer", models.CharField(max_length=30, verbose_name="Submitter")),
                (
                    "engineer_display",
                    models.CharField(
                        default="", max_length=50, verbose_name="Submitter Display Name"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("workflow_finish", "Workflow finished"),
                            ("workflow_abort", "Aborted"),
                            ("workflow_manreviewing", "Reviewing"),
                            ("workflow_review_pass", "Review passed"),
                            ("workflow_timingtask", "Scheduled"),
                            ("workflow_queuing", "Queuing"),
                            ("workflow_executing", "Executing"),
                            ("workflow_autoreviewwrong", "Rejected"),
                            ("workflow_exception", "Exceptions during execution"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "audit_auth_groups",
                    models.CharField(
                        max_length=255, verbose_name="Audit Authorization Groups"
                    ),
                ),
                (
                    "run_date_start",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Execution Start Time"
                    ),
                ),
                (
                    "run_date_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Execution End Time"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "finish_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Finished Time"
                    ),
                ),
                (
                    "is_manual",
                    models.IntegerField(
                        choices=[(0, "No"), (1, "Yes")],
                        default=0,
                        verbose_name="Manual Execution",
                    ),
                ),
                (
                    "is_offline_export",
                    models.IntegerField(
                        choices=[(0, "No"), (1, "Yes")],
                        default=0,
                        verbose_name="Offline Export Workflow",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("csv", "CSV"),
                            ("xlsx", "Excel"),
                            ("sql", "SQL"),
                            ("json", "JSON"),
                            ("xml", "XML"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Export Format",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="File Name"
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sql.instance"
                    ),
                ),
            ],
            options={
                "verbose_name": "SQL Workflow",
                "verbose_name_plural": "SQL Workflow",
                "db_table": "sql_workflow",
                "managed": True,
            },
            bases=(models.Model, sql.models.WorkflowAuditMixin),
        ),
        migrations.CreateModel(
            name="Tunnel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tunnel_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tunnel Name"
                    ),
                ),
                ("host", models.CharField(max_length=200, verbose_name="Tunnel Host")),
                ("port", models.IntegerField(default=0, verbose_name="Port")),
                (
                    "user",
                    mirage.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        max_length=200,
                        null=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "password",
                    mirage.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        max_length=300,
                        null=True,
                        verbose_name="Password",
                    ),
                ),
                (
                    "pkey",
                    mirage.fields.EncryptedTextField(
                        blank=True, null=True, verbose_name="Private Key"
                    ),
                ),
                (
                    "pkey_path",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="keys/",
                        verbose_name="Key File Path",
                    ),
                ),
                (
                    "pkey_password",
                    mirage.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        max_length=300,
                        null=True,
                        verbose_name="Key Passphrase",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
            ],
            options={
                "verbose_name": "Tunnel Configuration",
                "verbose_name_plural": "Tunnel Configuration",
                "db_table": "ssh_tunnel",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WorkflowAuditDetail",
            fields=[
                (
                    "audit_detail_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("audit_id", models.IntegerField(verbose_name="Audit Record ID")),
                ("audit_user", models.CharField(max_length=30, verbose_name="Auditor")),
                ("audit_time", models.DateTimeField(verbose_name="Audit Time")),
                (
                    "audit_status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending review"),
                            (1, "Approved"),
                            (2, "Rejected"),
                            (3, "Canceled"),
                        ],
                        verbose_name="Audit Status",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        default="", max_length=1000, verbose_name="Audit Remark"
                    ),
                ),
                (
                    "sys_time",
                    models.DateTimeField(auto_now=True, verbose_name="System Time"),
                ),
            ],
            options={
                "verbose_name": "Workflow Audit Detail",
                "verbose_name_plural": "Workflow Audit Detail",
                "db_table": "workflow_audit_detail",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WorkflowLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "audit_id",
                    models.IntegerField(
                        db_index=True, verbose_name="Workflow Audit ID"
                    ),
                ),
                (
                    "operation_type",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Submit"),
                            (1, "Approve"),
                            (2, "Reject"),
                            (3, "Cancel"),
                            (4, "Set scheduled execution"),
                            (5, "Start execution"),
                            (6, "Execution finished"),
                        ],
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "operation_type_desc",
                    models.CharField(
                        max_length=64, verbose_name="Operation Type Description"
                    ),
                ),
                (
                    "operation_info",
                    models.CharField(max_length=1000, verbose_name="Operation Info"),
                ),
                ("operator", models.CharField(max_length=30, verbose_name="Operator")),
                (
                    "operator_display",
                    models.CharField(
                        default="", max_length=50, verbose_name="Operator Display Name"
                    ),
                ),
                ("operation_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Workflow Log",
                "verbose_name_plural": "Workflow Log",
                "db_table": "workflow_log",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WorkflowAuditSetting",
            fields=[
                (
                    "audit_setting_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("group_id", models.IntegerField(verbose_name="Group ID")),
                (
                    "group_name",
                    models.CharField(max_length=100, verbose_name="Group Name"),
                ),
                (
                    "workflow_type",
                    models.IntegerField(
                        choices=[
                            (1, "Query privilege request"),
                            (2, "DDL/DML request"),
                            (3, "Data Archival request"),
                        ],
                        verbose_name="Audit Type",
                    ),
                ),
                (
                    "audit_auth_groups",
                    models.CharField(
                        max_length=255, verbose_name="Audit Authorization Groups"
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("sys_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Audit Flow Configuration",
                "verbose_name_plural": "Audit Flow Configuration",
                "db_table": "workflow_audit_setting",
                "managed": True,
                "unique_together": {("group_id", "workflow_type")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowAudit",
            fields=[
                ("audit_id", models.AutoField(primary_key=True, serialize=False)),
                ("group_id", models.IntegerField(verbose_name="Group ID")),
                (
                    "group_name",
                    models.CharField(max_length=100, verbose_name="Group Name"),
                ),
                (
                    "workflow_id",
                    models.BigIntegerField(verbose_name="Related Workflow ID"),
                ),
                (
                    "workflow_type",
                    models.IntegerField(
                        choices=[
                            (1, "Query privilege request"),
                            (2, "DDL/DML request"),
                            (3, "Data Archival request"),
                        ],
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "workflow_title",
                    models.CharField(max_length=50, verbose_name="Request Title"),
                ),
                (
                    "workflow_remark",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=140,
                        verbose_name="Request Remark",
                    ),
                ),
                (
                    "audit_auth_groups",
                    models.CharField(
                        max_length=255, verbose_name="Audit Authorization Groups"
                    ),
                ),
                (
                    "current_audit",
                    models.CharField(max_length=20, verbose_name="Current Audit Group"),
                ),
                (
                    "next_audit",
                    models.CharField(max_length=20, verbose_name="Next Audit Group"),
                ),
                (
                    "current_status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending review"),
                            (1, "Approved"),
                            (2, "Rejected"),
                            (3, "Canceled"),
                        ],
                        verbose_name="Audit Status",
                    ),
                ),
                (
                    "create_user",
                    models.CharField(max_length=30, verbose_name="Requester"),
                ),
                (
                    "create_user_display",
                    models.CharField(
                        default="", max_length=50, verbose_name="Requester Display Name"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Request Time"
                    ),
                ),
                (
                    "sys_time",
                    models.DateTimeField(auto_now=True, verbose_name="System Time"),
                ),
            ],
            options={
                "verbose_name": "Workflow Audit List",
                "verbose_name_plural": "Workflow Audit List",
                "db_table": "workflow_audit",
                "managed": True,
                "unique_together": {("workflow_id", "workflow_type")},
            },
        ),
        migrations.CreateModel(
            name="SqlWorkflowContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sql_content", models.TextField(verbose_name="SQL Content")),
                (
                    "review_content",
                    models.TextField(verbose_name="Auto Review Result (JSON)"),
                ),
                (
                    "execute_result",
                    models.TextField(
                        blank=True, verbose_name="Execution Result (JSON)"
                    ),
                ),
                (
                    "workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sql.sqlworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "SQL Workflow Content",
                "verbose_name_plural": "SQL Workflow Content",
                "db_table": "sql_workflow_content",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="QueryPrivilegesApply",
            fields=[
                ("apply_id", models.AutoField(primary_key=True, serialize=False)),
                ("group_id", models.IntegerField(verbose_name="Group ID")),
                (
                    "group_name",
                    models.CharField(max_length=100, verbose_name="Group Name"),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Request Title"),
                ),
                (
                    "user_name",
                    models.CharField(max_length=30, verbose_name="Requester"),
                ),
                (
                    "user_display",
                    models.CharField(
                        default="", max_length=50, verbose_name="Requester Display Name"
                    ),
                ),
                ("db_list", models.TextField(default="", verbose_name="Database")),
                ("table_list", models.TextField(default="", verbose_name="Table")),
                ("valid_date", models.DateField(verbose_name="Valid Until")),
                (
                    "limit_num",
                    models.IntegerField(default=100, verbose_name="Row Limit"),
                ),
                (
                    "priv_type",
                    models.IntegerField(
                        choices=[(1, "DATABASE"), (2, "TABLE")],
                        default=0,
                        verbose_name="Privilege Type",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending review"),
                            (1, "Approved"),
                            (2, "Rejected"),
                            (3, "Canceled"),
                        ],
                        verbose_name="Audit Status",
                    ),
                ),
                (
                    "audit_auth_groups",
                    models.CharField(
                        max_length=255, verbose_name="Audit Authorization Groups"
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("sys_time", models.DateTimeField(auto_now=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sql.instance"
                    ),
                ),
            ],
            options={
                "verbose_name": "Query Privilege Application",
                "verbose_name_plural": "Query Privilege Application",
                "db_table": "query_privileges_apply",
                "managed": True,
            },
            bases=(models.Model, sql.models.WorkflowAuditMixin),
        ),
        migrations.CreateModel(
            name="ParamTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "db_type",
                    models.CharField(
                        choices=[
                            ("mysql", "MySQL"),
                            ("mssql", "MsSQL"),
                            ("redis", "Redis"),
                            ("pgsql", "PgSQL"),
                            ("oracle", "Oracle"),
                            ("mongo", "Mongo"),
                            ("phoenix", "Phoenix"),
                            ("odps", "ODPS"),
                            ("clickhouse", "ClickHouse"),
                            ("goinception", "goInception"),
                            ("cassandra", "Cassandra"),
                            ("doris", "Doris"),
                            ("elasticsearch", "Elasticsearch"),
                            ("opensearch", "OpenSearch"),
                            ("memcached", "Memcached"),
                        ],
                        max_length=20,
                        verbose_name="Database Type",
                    ),
                ),
                (
                    "variable_name",
                    models.CharField(max_length=64, verbose_name="Parameter Name"),
                ),
                (
                    "default_value",
                    models.CharField(max_length=1024, verbose_name="Default Value"),
                ),
                (
                    "editable",
                    models.BooleanField(default=False, verbose_name="Editable"),
                ),
                (
                    "valid_values",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        verbose_name="Valid Values, e.g. range [1-65535] or enum [ON|OFF]",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        verbose_name="Parameter Description",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "sys_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="System Modified Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Parameter Template Configuration",
                "verbose_name_plural": "Instance Parameter Template Configuration",
                "db_table": "param_template",
                "managed": True,
                "unique_together": {("db_type", "variable_name")},
            },
        ),
        migrations.CreateModel(
            name="ParamHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variable_name",
                    models.CharField(max_length=64, verbose_name="Parameter Name"),
                ),
                (
                    "old_var",
                    models.CharField(max_length=1024, verbose_name="Old Value"),
                ),
                (
                    "new_var",
                    models.CharField(max_length=1024, verbose_name="New Value"),
                ),
                (
                    "set_sql",
                    models.CharField(
                        max_length=1024,
                        verbose_name="Executed SQL for Parameter Change",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=30, verbose_name="Modified By"),
                ),
                (
                    "user_display",
                    models.CharField(
                        max_length=50, verbose_name="Modifier Display Name"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Parameter Modified Time"
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sql.instance"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Parameter Change History",
                "verbose_name_plural": "Instance Parameter Change History",
                "db_table": "param_history",
                "ordering": ["-create_time"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="instance",
            name="instance_tag",
            field=models.ManyToManyField(
                blank=True, to="sql.instancetag", verbose_name="Instance Tag"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="resource_group",
            field=models.ManyToManyField(
                blank=True, to="sql.resourcegroup", verbose_name="Resource Group"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="tunnel",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sql.tunnel",
                verbose_name="Connection Tunnel",
            ),
        ),
        migrations.CreateModel(
            name="DataMaskingColumns",
            fields=[
                (
                    "column_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="Column ID"
                    ),
                ),
                (
                    "rule_type",
                    models.IntegerField(
                        choices=[
                            (1, "Phone Number"),
                            (2, "ID Number"),
                            (3, "Bank Card"),
                            (4, "Email"),
                            (5, "Amount"),
                            (6, "Other"),
                            (100, "Three-Segment Generic Masking Rule"),
                        ],
                        help_text="Three-segment generic masking rule: split by length and mask middle segment.",
                        verbose_name="Rule Type",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        choices=[(False, "Inactive"), (True, "Active")],
                        verbose_name="Active Status",
                    ),
                ),
                (
                    "table_schema",
                    models.CharField(max_length=64, verbose_name="Schema Name"),
                ),
                (
                    "table_name",
                    models.CharField(max_length=64, verbose_name="Table Name"),
                ),
                (
                    "column_name",
                    models.CharField(max_length=64, verbose_name="Column Name"),
                ),
                (
                    "column_comment",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="Column Description",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("sys_time", models.DateTimeField(auto_now=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sql.instance"
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Masking Column Configuration",
                "verbose_name_plural": "Data Masking Column Configuration",
                "db_table": "data_masking_columns",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ArchiveLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cmd",
                    models.CharField(max_length=2000, verbose_name="Archive Command"),
                ),
                (
                    "condition",
                    models.CharField(
                        max_length=1000, verbose_name="Archive Condition (WHERE clause)"
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("dest", "Other Instance"),
                            ("purge", "Direct Delete"),
                        ],
                        max_length=10,
                        verbose_name="Archive Mode",
                    ),
                ),
                ("no_delete", models.BooleanField(verbose_name="Retain Source Data")),
                (
                    "sleep",
                    models.IntegerField(
                        default=0, verbose_name="Sleep Seconds After Each Limited Batch"
                    ),
                ),
                ("select_cnt", models.IntegerField(verbose_name="Selected Rows")),
                ("insert_cnt", models.IntegerField(verbose_name="Inserted Rows")),
                ("delete_cnt", models.IntegerField(verbose_name="Deleted Rows")),
                ("statistics", models.TextField(verbose_name="Archive Statistics Log")),
                ("success", models.BooleanField(verbose_name="Archive Succeeded")),
                ("error_info", models.TextField(verbose_name="Error Info")),
                ("start_time", models.DateTimeField(verbose_name="Start Time")),
                ("end_time", models.DateTimeField(verbose_name="End Time")),
                (
                    "sys_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="System Modified Time"
                    ),
                ),
                (
                    "archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sql.archiveconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archive Log",
                "verbose_name_plural": "Archive Log",
                "db_table": "archive_log",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="dest_instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dest_instance",
                to="sql.instance",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="resource_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sql.resourcegroup"
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="src_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="src_instance",
                to="sql.instance",
            ),
        ),
        migrations.CreateModel(
            name="AliyunRdsConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rds_dbinstanceid",
                    models.CharField(
                        max_length=100, verbose_name="Alibaba Cloud RDS Instance ID"
                    ),
                ),
                (
                    "is_enable",
                    models.BooleanField(default=False, verbose_name="Enabled"),
                ),
                (
                    "ak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sql.cloudaccesskey",
                        verbose_name="RDS Access Key Configuration",
                    ),
                ),
                (
                    "instance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="sql.instance"
                    ),
                ),
            ],
            options={
                "verbose_name": "Alibaba Cloud RDS Configuration",
                "verbose_name_plural": "Alibaba Cloud RDS Configuration",
                "db_table": "aliyun_rds_config",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        default="", max_length=50, verbose_name="Display Name"
                    ),
                ),
                (
                    "ding_user_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="DingTalk User ID"
                    ),
                ),
                (
                    "wx_user_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="WeCom User ID"
                    ),
                ),
                (
                    "feishu_open_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Feishu Open ID"
                    ),
                ),
                (
                    "failed_login_count",
                    models.IntegerField(default=0, verbose_name="Failed Login Count"),
                ),
                (
                    "last_login_failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Failed Login Time"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "resource_group",
                    models.ManyToManyField(
                        blank=True,
                        to="sql.resourcegroup",
                        verbose_name="Resource Group",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Management",
                "verbose_name_plural": "User Management",
                "db_table": "sql_users",
                "managed": True,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="TwoFactorAuthConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    mirage.fields.EncryptedCharField(
                        max_length=200, verbose_name="Username"
                    ),
                ),
                (
                    "auth_type",
                    mirage.fields.EncryptedCharField(
                        choices=[
                            ("totp", "Google Authenticator"),
                            ("sms", "SMS Verification Code"),
                        ],
                        max_length=128,
                        verbose_name="Authentication Type",
                    ),
                ),
                (
                    "phone",
                    mirage.fields.EncryptedCharField(
                        default="",
                        max_length=64,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "secret_key",
                    mirage.fields.EncryptedCharField(
                        max_length=256, null=True, verbose_name="User Secret"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "2FA Configuration",
                "verbose_name_plural": "2FA Configuration",
                "db_table": "2fa_config",
                "managed": True,
                "unique_together": {("user", "auth_type")},
            },
        ),
        migrations.CreateModel(
            name="QueryPrivileges",
            fields=[
                ("privilege_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=30, verbose_name="Username")),
                (
                    "user_display",
                    models.CharField(
                        default="", max_length=50, verbose_name="Requester Display Name"
                    ),
                ),
                (
                    "db_name",
                    models.CharField(
                        default="", max_length=64, verbose_name="Database"
                    ),
                ),
                (
                    "table_name",
                    models.CharField(default="", max_length=64, verbose_name="Table"),
                ),
                ("valid_date", models.DateField(verbose_name="Valid Until")),
                (
                    "limit_num",
                    models.IntegerField(default=100, verbose_name="Row Limit"),
                ),
                (
                    "priv_type",
                    models.IntegerField(
                        choices=[(1, "DATABASE"), (2, "TABLE")],
                        default=0,
                        verbose_name="Privilege Type",
                    ),
                ),
                (
                    "is_deleted",
                    models.IntegerField(default=0, verbose_name="Is Deleted"),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("sys_time", models.DateTimeField(auto_now=True)),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sql.instance"
                    ),
                ),
            ],
            options={
                "verbose_name": "Query Privilege Record",
                "verbose_name_plural": "Query Privilege Record",
                "db_table": "query_privileges",
                "managed": True,
                "index_together": {("user_name", "instance", "db_name", "valid_date")},
            },
        ),
        migrations.CreateModel(
            name="InstanceDatabase",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "db_name",
                    models.CharField(max_length=128, verbose_name="Database Name"),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Owner"
                    ),
                ),
                (
                    "owner_display",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        verbose_name="Owner Display Name",
                    ),
                ),
                (
                    "remark",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Remark"
                    ),
                ),
                (
                    "sys_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="System Modified Time"
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sql.instance"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Database",
                "verbose_name_plural": "Instance Database List",
                "db_table": "instance_database",
                "managed": True,
                "unique_together": {("instance", "db_name")},
            },
        ),
        migrations.CreateModel(
            name="InstanceAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    mirage.fields.EncryptedCharField(
                        max_length=128, verbose_name="Account"
                    ),
                ),
                ("host", models.CharField(max_length=64, verbose_name="Host")),
                (
                    "db_name",
                    models.CharField(max_length=128, verbose_name="Database Name"),
                ),
                (
                    "password",
                    mirage.fields.EncryptedCharField(
                        blank=True, default="", max_length=128, verbose_name="Password"
                    ),
                ),
                ("remark", models.CharField(max_length=255, verbose_name="Remark")),
                (
                    "sys_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="System Modified Time"
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sql.instance"
                    ),
                ),
            ],
            options={
                "verbose_name": "Instance Account List",
                "verbose_name_plural": "Instance Account List",
                "db_table": "instance_account",
                "managed": True,
                "unique_together": {("instance", "user", "host", "db_name")},
            },
        ),
    ]
