# Generated by Django 4.1.13 on 2026-04-02 22:13

import base64
import common.fields.encrypted
from Crypto.Cipher import AES
from binascii import a2b_hex
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from django.db import migrations, models
from django.utils.encoding import force_bytes, force_str


def _decrypt_mirage(value, secret_key=None, cipher_mode=None, cipher_iv=None):
    from django.conf import settings

    key = secret_key or getattr(settings, "MIRAGE_SECRET_KEY", None)
    if not key:
        return None
    cipher_key = base64.urlsafe_b64encode(force_bytes(key))[:32]
    if len(cipher_key) not in (16, 24, 32):
        return None
    cipher_mode = (
        cipher_mode or getattr(settings, "MIRAGE_CIPHER_MODE", "ECB")
    ).upper()
    iv = force_bytes(
        cipher_iv or getattr(settings, "MIRAGE_CIPHER_IV", "1234567890abcdef")
    )
    if cipher_mode == "CBC":
        mode = modes.CBC(iv)
    else:
        mode = modes.ECB()
    cipher = Cipher(algorithms.AES(cipher_key), mode, default_backend()).decryptor()
    unpadder = padding.PKCS7(algorithms.AES(cipher_key).block_size).unpadder()
    plaintext = cipher.update(base64.urlsafe_b64decode(force_bytes(value)))
    plaintext += cipher.finalize()
    return force_str(unpadder.update(plaintext) + unpadder.finalize())


def _decrypt_old_hex(value):
    if len(value) < 32 or len(value) % 2 != 0:
        return None

    try:
        cryptor = AES.new(
            b"eCcGFZQj6PNoSSma31LR39rTzTbLkU8E", AES.MODE_CBC, b"0000000000000000"
        )
        plain_text = cryptor.decrypt(a2b_hex(value))
        return plain_text.decode().rstrip("\0")
    except Exception:
        return None


def _decrypt_legacy_value(value, secret_key, cipher_mode=None, cipher_iv=None):
    if value in ("", None):
        return value

    for decryptor in (
        lambda ciphertext: _decrypt_mirage(
            ciphertext, secret_key, cipher_mode, cipher_iv
        ),
        _decrypt_old_hex,
    ):
        try:
            plaintext = decryptor(value)
        except Exception:
            plaintext = None
        if plaintext is not None:
            return plaintext

    raise ValueError(
        "Unable to decrypt legacy InstanceAccount.user value "
        f"marker={value[:16]!r} length={len(value)}"
    )


def decrypt_instanceaccount_user(apps, schema_editor):
    InstanceAccount = apps.get_model("sql", "InstanceAccount")
    from django.conf import settings

    secret_key = getattr(settings, "MIRAGE_SECRET_KEY", None) or settings.SECRET_KEY
    cipher_mode = getattr(settings, "MIRAGE_CIPHER_MODE", "ECB")
    cipher_iv = getattr(settings, "MIRAGE_CIPHER_IV", "1234567890abcdef")

    for account in InstanceAccount.objects.using(schema_editor.connection.alias).all():
        if account.user in ("", None):
            continue
        plaintext = _decrypt_legacy_value(
            account.user, secret_key, cipher_mode, cipher_iv
        )
        InstanceAccount.objects.using(schema_editor.connection.alias).filter(
            pk=account.pk
        ).update(user=plaintext)


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0002_permissionrequest_alter_workflowaudit_workflow_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcegroup",
            name="ding_webhook",
        ),
        migrations.RemoveField(
            model_name="twofactorauthconfig",
            name="username",
        ),
        migrations.RemoveField(
            model_name="users",
            name="ding_user_id",
        ),
        migrations.AlterField(
            model_name="cloudaccesskey",
            name="key_id",
            field=common.fields.encrypted.EncryptedCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="cloudaccesskey",
            name="key_secret",
            field=common.fields.encrypted.EncryptedCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="config",
            name="value",
            field=common.fields.encrypted.EncryptedCharField(
                max_length=500, verbose_name="Config Value"
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="password",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True, default="", max_length=300, verbose_name="Password"
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="user",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True, default="", max_length=200, verbose_name="Username"
            ),
        ),
        migrations.AlterField(
            model_name="instanceaccount",
            name="password",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True, default="", max_length=128, verbose_name="Password"
            ),
        ),
        migrations.RunPython(decrypt_instanceaccount_user, noop_reverse),
        migrations.AlterField(
            model_name="instanceaccount",
            name="user",
            field=models.CharField(max_length=128, verbose_name="Account"),
        ),
        migrations.AlterField(
            model_name="tunnel",
            name="password",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True,
                default="",
                max_length=300,
                null=True,
                verbose_name="Password",
            ),
        ),
        migrations.AlterField(
            model_name="tunnel",
            name="pkey",
            field=common.fields.encrypted.EncryptedTextField(
                blank=True, null=True, verbose_name="Private Key"
            ),
        ),
        migrations.AlterField(
            model_name="tunnel",
            name="pkey_password",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True,
                default="",
                max_length=300,
                null=True,
                verbose_name="Key Passphrase",
            ),
        ),
        migrations.AlterField(
            model_name="tunnel",
            name="user",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="Username",
            ),
        ),
        migrations.AlterField(
            model_name="twofactorauthconfig",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("totp", "Google Authenticator"),
                    ("sms", "SMS Verification Code"),
                ],
                max_length=128,
                verbose_name="Authentication Type",
            ),
        ),
        migrations.AlterField(
            model_name="twofactorauthconfig",
            name="phone",
            field=common.fields.encrypted.EncryptedCharField(
                default="", max_length=64, null=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="twofactorauthconfig",
            name="secret_key",
            field=common.fields.encrypted.EncryptedCharField(
                max_length=256, null=True, verbose_name="User Secret"
            ),
        ),
    ]
