# Generated by Django 4.1.13 on 2026-04-02 22:13

import common.fields.encrypted
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0002_permissionrequest_alter_workflowaudit_workflow_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resourcegroup",
            name="ding_webhook",
        ),
        migrations.RemoveField(
            model_name="twofactorauthconfig",
            name="username",
        ),
        migrations.RemoveField(
            model_name="users",
            name="ding_user_id",
        ),
        migrations.AlterField(
            model_name="cloudaccesskey",
            name="key_id",
            field=common.fields.encrypted.EncryptedCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="cloudaccesskey",
            name="key_secret",
            field=common.fields.encrypted.EncryptedCharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="config",
            name="value",
            field=common.fields.encrypted.EncryptedCharField(
                max_length=500, verbose_name="Config Value"
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="password",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True, default="", max_length=300, verbose_name="Password"
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="user",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True, default="", max_length=200, verbose_name="Username"
            ),
        ),
        migrations.AlterField(
            model_name="instanceaccount",
            name="password",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True, default="", max_length=128, verbose_name="Password"
            ),
        ),
        migrations.AlterField(
            model_name="instanceaccount",
            name="user",
            field=models.CharField(max_length=128, verbose_name="Account"),
        ),
        migrations.AlterField(
            model_name="tunnel",
            name="password",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True,
                default="",
                max_length=300,
                null=True,
                verbose_name="Password",
            ),
        ),
        migrations.AlterField(
            model_name="tunnel",
            name="pkey",
            field=common.fields.encrypted.EncryptedTextField(
                blank=True, null=True, verbose_name="Private Key"
            ),
        ),
        migrations.AlterField(
            model_name="tunnel",
            name="pkey_password",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True,
                default="",
                max_length=300,
                null=True,
                verbose_name="Key Passphrase",
            ),
        ),
        migrations.AlterField(
            model_name="tunnel",
            name="user",
            field=common.fields.encrypted.EncryptedCharField(
                blank=True,
                default="",
                max_length=200,
                null=True,
                verbose_name="Username",
            ),
        ),
        migrations.AlterField(
            model_name="twofactorauthconfig",
            name="auth_type",
            field=models.CharField(
                choices=[
                    ("totp", "Google Authenticator"),
                    ("sms", "SMS Verification Code"),
                ],
                max_length=128,
                verbose_name="Authentication Type",
            ),
        ),
        migrations.AlterField(
            model_name="twofactorauthconfig",
            name="phone",
            field=common.fields.encrypted.EncryptedCharField(
                default="", max_length=64, null=True, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="twofactorauthconfig",
            name="secret_key",
            field=common.fields.encrypted.EncryptedCharField(
                max_length=256, null=True, verbose_name="User Secret"
            ),
        ),
    ]
