# Generated by Django 6.0.3 on 2026-04-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0009_taskschedule"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="taskschedule",
            index=models.Index(fields=["status", "run_at"], name="idx_status_run_at"),
        ),
    ]
