# Generated by Django 6.0.3 on 2026-04-20 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0012_archiveconfig_consecutive_failures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliyunrdsconfig',
            name='ak',
        ),
        migrations.RemoveField(
            model_name='aliyunrdsconfig',
            name='instance',
        ),
        migrations.RemoveField(
            model_name='instance',
            name='tunnel',
        ),
        migrations.DeleteModel(
            name='CloudAccessKey',
        ),
        migrations.DeleteModel(
            name='AliyunRdsConfig',
        ),
        migrations.DeleteModel(
            name='Tunnel',
        ),
    ]
