# Generated by Django 6.0.3 on 2026-04-25 18:50

from django.db import migrations

RETIRED_SQL_PERMISSION_CODENAMES = (
    "menu_sqlanalyze",
    "menu_sqloptimize",
    "menu_sqladvisor",
    "menu_slowquery",
    "menu_my2sql",
    "menu_schemasync",
    "menu_document",
    "sql_analyze",
    "optimize_sqladvisor",
    "optimize_sqltuning",
    "optimize_soar",
)


def remove_retired_sql_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="sql", codename__in=RETIRED_SQL_PERMISSION_CODENAMES
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0014_mailboxitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="permission",
            options={
                "managed": True,
                "permissions": (
                    ("menu_dashboard", "Menu Dashboard"),
                    ("menu_sqlcheck", "Menu SQL Review"),
                    ("menu_sqlworkflow", "Menu SQL Deployment"),
                    ("menu_query", "Menu SQL Query"),
                    ("menu_sqlquery", "Menu Online Query"),
                    ("menu_queryapplylist", "Menu Privilege Management"),
                    ("menu_instance", "Menu Instance Management"),
                    ("menu_instance_list", "Menu Instance List"),
                    ("menu_dbdiagnostic", "Menu Session Management"),
                    ("menu_database", "Menu Database Management"),
                    ("menu_instance_account", "Menu Instance Account Management"),
                    ("menu_param", "Menu Parameter Configuration"),
                    ("menu_data_dictionary", "Menu Data Dictionary"),
                    ("menu_tools", "Menu Tool Plugins"),
                    ("menu_archive", "Menu Data Archive"),
                    ("menu_system", "Menu System Management"),
                    ("menu_openapi", "Menu OpenAPI"),
                    ("sql_submit", "Submit SQL Deployment Workflow"),
                    ("sql_review", "Review SQL Deployment Workflow"),
                    (
                        "sql_execute_for_resource_group",
                        "Execute SQL Deployment Workflow (Resource Group Scope)",
                    ),
                    (
                        "sql_execute",
                        "Execute SQL Deployment Workflow (Own Submissions Only)",
                    ),
                    ("query_applypriv", "Apply Query Privileges"),
                    ("query_mgtpriv", "Manage Query Privileges"),
                    ("query_review", "Review Query Privileges"),
                    ("query_submit", "Submit SQL Query"),
                    ("query_all_instances", "Query All Instances"),
                    (
                        "query_resource_group_instance",
                        "Query All Instances in Resource Group",
                    ),
                    ("process_view", "View Sessions"),
                    ("process_kill", "Kill Sessions"),
                    ("tablespace_view", "View Tablespaces"),
                    ("trx_view", "View Transaction Info"),
                    ("trxandlocks_view", "View Lock Info"),
                    ("instance_account_manage", "Manage Instance Accounts"),
                    ("param_view", "View Instance Parameters"),
                    ("param_edit", "Edit Instance Parameters"),
                    ("data_dictionary_export", "Export Data Dictionary"),
                    ("archive_apply", "Submit Archive Request"),
                    ("archive_review", "Review Archive Request"),
                    ("archive_mgt", "Manage Archive Request"),
                    ("audit_user", "Audit Permission"),
                    ("query_download", "Online Query Download Permission"),
                    ("offline_download", "Offline Download Permission"),
                    ("menu_sqlexportworkflow", "Menu Data Export"),
                    ("sqlexport_submit", "Submit Data Export"),
                ),
            },
        ),
        migrations.RunPython(remove_retired_sql_permissions, migrations.RunPython.noop),
    ]
