# Generated by Django 6.0.3 on 2026-05-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql', '0016_instance_inventory_detected_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskschedule',
            name='backend',
            field=models.CharField(choices=[('celery', 'Celery')], default='celery', max_length=20, verbose_name='Task Backend'),
        ),
    ]
