apiVersion: 1
prune: true

deleteDatasources:
  - name: Prometheus Local
    orgId: 1

datasources:
  - name: VictoriaMetrics local-dev
    type: prometheus
    access: proxy
    url: http://victoriametrics-local-dev:8428/prometheus
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Quickwit Traces
    type: quickwit-quickwit-datasource
    access: proxy
    url: http://quickwit:7280/api/v1
    jsonData:
      index: otel-traces-v0_7

  - name: Quickwit Logs
    type: quickwit-quickwit-datasource
    access: proxy
    url: http://quickwit:7280/api/v1
    jsonData:
      index: otel-logs-v0_7
      logMessageField: body
      logLevelField: severity_text

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger-query:16686
