# Generated by Django 6.0.3 on 2026-04-03 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0003_remove_resourcegroup_ding_webhook_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="queryprivileges",
            new_name="query_privilege_lookup_idx",
            old_fields=("user_name", "instance", "db_name", "valid_date"),
        ),
    ]
