# Generated by Django 6.0.3 on 2026-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0006_sqlworkflow_schema_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="workos_user_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="WorkOS User ID",
            ),
        ),
    ]
