# Generated by Django 6.0.3 on 2026-04-14 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0007_users_workos_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="avatar_url",
            field=models.URLField(
                blank=True, default="", max_length=500, verbose_name="Avatar URL"
            ),
        ),
    ]
