# Generated by Django 6.0.3 on 2026-04-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0008_users_avatar_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Schedule Name"
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[("django_q", "Django Q"), ("celery", "Celery")],
                        default="django_q",
                        max_length=20,
                        verbose_name="Task Backend",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Task Name"
                    ),
                ),
                (
                    "callable_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Callable Path",
                    ),
                ),
                (
                    "payload",
                    models.TextField(
                        blank=True, default="", verbose_name="Serialized Payload"
                    ),
                ),
                ("run_at", models.DateTimeField(verbose_name="Scheduled Run Time")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Schedule Status",
                    ),
                ),
                (
                    "backend_job_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Backend Job ID",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, default="", verbose_name="Last Error"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Completed At"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Cancelled At"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "sys_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="System Modified Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduled Task",
                "verbose_name_plural": "Scheduled Task",
                "db_table": "task_schedule",
                "managed": True,
            },
        ),
    ]
