# Generated by Django 6.0.3 on 2026-04-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0010_taskschedule_idx_status_run_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveconfig",
            name="archive_method",
            field=models.CharField(
                choices=[
                    ("dml", "Rendered DML Delete"),
                    ("pt_archiver", "pt-archiver"),
                ],
                default="pt_archiver",
                max_length=20,
                verbose_name="Archive Method",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="execution_mode",
            field=models.CharField(
                choices=[("one_time", "One Time"), ("scheduled", "Scheduled")],
                default="one_time",
                max_length=20,
                verbose_name="Execution Mode",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="next_run_at",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Next Run Time"
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="schedule_frequency",
            field=models.CharField(
                blank=True,
                choices=[("daily", "Daily"), ("weekly", "Weekly")],
                default=None,
                max_length=20,
                null=True,
                verbose_name="Schedule Frequency",
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="schedule_time",
            field=models.TimeField(
                blank=True, default=None, null=True, verbose_name="Schedule Time"
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="schedule_weekdays",
            field=models.CharField(
                blank=True, default="", max_length=32, verbose_name="Schedule Weekdays"
            ),
        ),
        migrations.AddField(
            model_name="archivelog",
            name="archive_method",
            field=models.CharField(
                choices=[
                    ("dml", "Rendered DML Delete"),
                    ("pt_archiver", "pt-archiver"),
                ],
                default="pt_archiver",
                max_length=20,
                verbose_name="Archive Method",
            ),
        ),
    ]
