# Generated by Django 6.0.3 on 2026-04-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0011_archiveconfig_archive_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveconfig",
            name="consecutive_failures",
            field=models.IntegerField(
                default=0, verbose_name="Consecutive Scheduled Failures"
            ),
        ),
        migrations.AddField(
            model_name="archiveconfig",
            name="execution_state",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("queued", "Queued"),
                    ("running", "Running"),
                ],
                default="idle",
                max_length=20,
                verbose_name="Execution State",
            ),
        ),
    ]
