# Generated by Django 6.0.3 on 2026-04-22 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0013_remove_aliyunrdsconfig_ak_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailboxItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("approval_needed", "Approval needed"),
                            ("execution_needed", "Execution needed"),
                            ("execution_finished", "Execution finished"),
                        ],
                        max_length=32,
                        verbose_name="Mailbox Category",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("sql_workflow", "SQL Workflow"),
                            ("archive", "Archive"),
                            ("permission_request", "Permission Request"),
                        ],
                        max_length=32,
                        verbose_name="Mailbox Source Type",
                    ),
                ),
                ("source_id", models.BigIntegerField(verbose_name="Mailbox Source ID")),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Mailbox Title"),
                ),
                (
                    "body",
                    models.TextField(
                        blank=True, default="", verbose_name="Mailbox Body"
                    ),
                ),
                (
                    "action_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Mailbox Action Path"
                    ),
                ),
                ("is_unread", models.BooleanField(default=True, verbose_name="Unread")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Read At"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "dedupe_key",
                    models.CharField(max_length=255, verbose_name="Dedupe Key"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "sys_time",
                    models.DateTimeField(
                        auto_now=True, verbose_name="System Modified Time"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mailbox_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mailbox Item",
                "verbose_name_plural": "Mailbox Items",
                "db_table": "mailbox_item",
                "ordering": ["-create_time", "-id"],
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_unread", "create_time"],
                        name="mailbox_item_unread_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_id", "category"],
                        name="mailbox_item_source_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipient", "dedupe_key"),
                        name="mailbox_item_recipient_dedupe_uniq",
                    )
                ],
            },
        ),
    ]
