# Generated by Django 6.0.3 on 2026-04-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0015_alter_permission_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="inventory_detected_hostname",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Inventory Detected Hostname",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="inventory_detected_version",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Inventory Detected Version",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="inventory_last_attempt_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Inventory Last Attempt At",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="inventory_last_success_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Inventory Last Success At",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="inventory_status",
            field=models.CharField(
                choices=[
                    ("never", "Never"),
                    ("ok", "OK"),
                    ("stale", "Stale"),
                    ("failed", "Failed"),
                ],
                default="never",
                max_length=20,
                verbose_name="Inventory Refresh Status",
            ),
        ),
    ]
