# Generated by Django 6.0.3 on 2026-05-15 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0017_alter_taskschedule_backend"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="execution_mode",
            field=models.CharField(
                choices=[("agent", "Agent")],
                default="agent",
                max_length=20,
                verbose_name="Execution Mode",
            ),
        ),
        migrations.CreateModel(
            name="InfrastructureNode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Node Name"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Node Address"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "resource_group",
                    models.ManyToManyField(
                        blank=True,
                        to="sql.resourcegroup",
                        verbose_name="Resource Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Infrastructure Node",
                "verbose_name_plural": "Infrastructure Nodes",
                "db_table": "infrastructure_node",
                "permissions": (
                    ("menu_infrastructure", "Can access Infrastructure menu"),
                ),
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="instance",
            name="node",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="sql.infrastructurenode",
                verbose_name="Infrastructure Node",
            ),
        ),
        migrations.CreateModel(
            name="ServiceRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        choices=[("mysql", "MySQL"), ("pgsql", "PostgreSQL")],
                        max_length=20,
                        verbose_name="Service Engine",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Host"
                    ),
                ),
                ("port", models.IntegerField(default=0, verbose_name="Port")),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=128,
                        verbose_name="Service Name",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Discovery Source",
                    ),
                ),
                (
                    "confidence",
                    models.PositiveSmallIntegerField(
                        default=50, verbose_name="Confidence"
                    ),
                ),
                (
                    "detected_version",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Detected Version",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(max_length=128, verbose_name="Fingerprint"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recommended", "Recommended"),
                            ("accepted", "Accepted"),
                            ("ignored", "Ignored"),
                        ],
                        db_index=True,
                        default="recommended",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Seen At"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_recommendations",
                        to="sql.infrastructurenode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Recommendation",
                "verbose_name_plural": "Service Recommendations",
                "db_table": "service_recommendation",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["node", "status"], name="svc_rec_node_status_idx"
                    ),
                    models.Index(
                        fields=["engine", "host", "port"], name="svc_rec_endpoint_idx"
                    ),
                ],
                "unique_together": {("node", "fingerprint")},
            },
        ),
    ]
