# Generated by Django 6.0.3 on 2026-05-18 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0017_alter_taskschedule_backend"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOSDirectorySyncEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="WorkOS Event ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(max_length=128, verbose_name="WorkOS Event Type"),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "WorkOS Directory Sync Event",
                "verbose_name_plural": "WorkOS Directory Sync Events",
                "db_table": "workos_directory_sync_event",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="access_duration",
            field=models.CharField(
                choices=[("temporary", "Temporary"), ("permanent", "Permanent")],
                default="temporary",
                max_length=32,
                verbose_name="Access Duration",
            ),
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="subject_type",
            field=models.CharField(
                choices=[("user", "User"), ("resource_group", "Resource Group")],
                default="user",
                max_length=32,
                verbose_name="Request Subject Type",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="workos_directory_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=64,
                verbose_name="WorkOS Directory ID",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="workos_directory_managed",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="WorkOS Directory Managed"
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="workos_directory_user_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="WorkOS Directory User ID",
            ),
        ),
        migrations.AlterField(
            model_name="temporaryinstancegrant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PermanentResourceGroupGrant",
            fields=[
                ("grant_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "is_revoked",
                    models.BooleanField(default=False, verbose_name="Revoked"),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("sys_time", models.DateTimeField(auto_now=True)),
                (
                    "instance",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sql.instance",
                    ),
                ),
                (
                    "resource_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sql.resourcegroup",
                    ),
                ),
                (
                    "source_request",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sql.permissionrequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Permanent Resource Group Grant",
                "verbose_name_plural": "Permanent Resource Group Grants",
                "db_table": "permanent_resource_group_grant",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WorkOSDirectoryGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workos_group_id",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="WorkOS Directory Group ID",
                    ),
                ),
                (
                    "directory_id",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="WorkOS Directory ID"
                    ),
                ),
                (
                    "organization_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        max_length=64,
                        verbose_name="WorkOS Organization ID",
                    ),
                ),
                (
                    "idp_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Identity Provider Group ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="WorkOS Group Name"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="Deleted in WorkOS"
                    ),
                ),
                ("workos_updated_at", models.DateTimeField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("sys_time", models.DateTimeField(auto_now=True)),
                (
                    "resource_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workos_directory_mappings",
                        to="sql.resourcegroup",
                        verbose_name="Resource Group",
                    ),
                ),
            ],
            options={
                "verbose_name": "WorkOS Directory Group",
                "verbose_name_plural": "WorkOS Directory Groups",
                "db_table": "workos_directory_group",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="WorkOSDirectoryGroupMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("sys_time", models.DateTimeField(auto_now=True)),
                (
                    "directory_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="sql.workosdirectorygroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workos_directory_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "WorkOS Directory Group Membership",
                "verbose_name_plural": "WorkOS Directory Group Memberships",
                "db_table": "workos_directory_group_membership",
                "managed": True,
                "unique_together": {("user", "directory_group")},
            },
        ),
    ]
