# Generated by Django 6.0.3 on 2026-05-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0018_workosdirectorysyncevent_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="permanentresourcegroupgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("user__isnull", False),
                    ("instance__isnull", False),
                    _connector="OR",
                ),
                name="permanent_rg_grant_has_user_or_instance",
            ),
        ),
    ]
