# Generated by Codex on 2026-05-14

import hashlib
import re

from django.db import migrations


def _node_name_for_address(address, used_names):
    raw = address or "unassigned"
    slug = re.sub(r"[^A-Za-z0-9_.-]+", "-", raw).strip(".-") or "unassigned"
    fingerprint = hashlib.sha256(raw.encode("utf-8")).hexdigest()[:8]
    base = f"node-{slug}"[:118].strip(".-")
    name = f"{base}-{fingerprint}"
    suffix = 1
    candidate = name
    while candidate in used_names:
        suffix += 1
        candidate = f"{name[:123]}-{suffix}"
    used_names.add(candidate)
    return candidate


def group_instances_into_nodes(apps, schema_editor):
    InfrastructureNode = apps.get_model("sql", "InfrastructureNode")
    Instance = apps.get_model("sql", "Instance")
    db_alias = schema_editor.connection.alias

    used_names = set(
        InfrastructureNode.objects.using(db_alias).values_list("name", flat=True)
    )
    nodes_by_address = {
        node.address: node for node in InfrastructureNode.objects.using(db_alias).all()
    }

    for instance in (
        Instance.objects.using(db_alias)
        .filter(node__isnull=True)
        .prefetch_related("resource_group")
        .order_by("id")
    ):
        address = (instance.host or "").strip() or "unassigned"
        node = nodes_by_address.get(address)
        if node is None:
            node = InfrastructureNode.objects.using(db_alias).create(
                name=_node_name_for_address(address, used_names),
                address=address,
                description="Created from existing database service inventory.",
                metadata={"source": "migration", "grouped_by": "host"},
            )
            nodes_by_address[address] = node
        instance.node_id = node.id
        instance.execution_mode = "agent"
        instance.save(update_fields=["node", "execution_mode"])
        groups = list(instance.resource_group.all())
        if groups:
            node.resource_group.add(*groups)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0018_instance_execution_mode_infrastructurenode_and_more"),
    ]

    operations = [
        migrations.RunPython(group_instances_into_nodes, noop_reverse),
    ]
