# Generated by Django 6.0.3 on 2026-05-20 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sql",
            "0019_permanentresourcegroupgrant_permanent_rg_grant_has_user_or_instance",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InfrastructureNode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "node_name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Node Name"
                    ),
                ),
                (
                    "hostname",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Hostname"
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=64,
                        verbose_name="Environment",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Provider"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Enabled")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
            ],
            options={
                "verbose_name": "Infrastructure Node",
                "verbose_name_plural": "Infrastructure Nodes",
                "db_table": "infrastructure_node",
                "ordering": ("node_name", "id"),
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="instance",
            name="node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to="sql.infrastructurenode",
                verbose_name="Infrastructure Node",
            ),
        ),
    ]
