# Generated by Django 6.0.3 on 2026-05-26 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0019_group_existing_instances_into_nodes"),
        (
            "sql",
            "0019_permanentresourcegroupgrant_permanent_rg_grant_has_user_or_instance",
        ),
    ]

    operations = []
