# Generated by Django 6.0.3 on 2026-05-26 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_agents", "0009_remove_agent_node_remove_agentcommand_node_and_more"),
        ("sql", "0020_merge_20260526_2116"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="infrastructurenode",
            name="resource_group",
        ),
        migrations.RemoveField(
            model_name="instance",
            name="node",
        ),
        migrations.AlterUniqueTogether(
            name="servicerecommendation",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="servicerecommendation",
            name="svc_rec_node_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="servicerecommendation",
            name="svc_rec_endpoint_idx",
        ),
        migrations.RemoveField(
            model_name="instance",
            name="execution_mode",
        ),
        migrations.RemoveField(
            model_name="servicerecommendation",
            name="node",
        ),
        migrations.DeleteModel(
            name="InfrastructureNode",
        ),
        migrations.DeleteModel(
            name="ServiceRecommendation",
        ),
    ]
