# Generated by Django 6.0.3 on 2026-05-28 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

ROLE_QUERY = "query"
ROLE_WORKFLOW_REQUESTER = "workflow_requester"
ROLE_WORKFLOW_APPROVER = "workflow_approver"
ROLE_RESOURCE_OWNER = "resource_owner"
SOURCE_DATAMINGLE = "datamingle"
SOURCE_WORKOS_DIRECTORY = "workos_directory"

ROLE_RANKS = {
    ROLE_QUERY: 10,
    ROLE_WORKFLOW_REQUESTER: 20,
    ROLE_WORKFLOW_APPROVER: 30,
    ROLE_RESOURCE_OWNER: 40,
}

LEGACY_GROUP_ROLE_MAP = {
    "DBA": ROLE_RESOURCE_OWNER,
    "PM": ROLE_WORKFLOW_APPROVER,
    "RD": ROLE_WORKFLOW_REQUESTER,
    "QA": ROLE_QUERY,
    "Default": ROLE_QUERY,
}


def _highest_role_for_group_names(group_names):
    matched_roles = [
        LEGACY_GROUP_ROLE_MAP[group_name]
        for group_name in group_names
        if group_name in LEGACY_GROUP_ROLE_MAP
    ]
    if not matched_roles:
        return ROLE_QUERY
    return max(matched_roles, key=lambda role: ROLE_RANKS[role])


def _normalize_approval_token(token, groups_by_id, groups_by_name):
    value = str(token or "").strip()
    if not value:
        return ""
    if value in ROLE_RANKS:
        return value
    if value in LEGACY_GROUP_ROLE_MAP:
        return LEGACY_GROUP_ROLE_MAP[value]

    group_name = ""
    if value.isdigit():
        group_name = groups_by_id.get(int(value), "")
    if not group_name:
        group_name = groups_by_name.get(value, "")
    if group_name:
        return LEGACY_GROUP_ROLE_MAP.get(group_name, ROLE_WORKFLOW_APPROVER)

    return ROLE_WORKFLOW_APPROVER


def _normalize_approval_sequence(raw_value, groups_by_id, groups_by_name):
    if raw_value in (None, ""):
        return ""
    roles = []
    for token in str(raw_value).split(","):
        role = _normalize_approval_token(token, groups_by_id, groups_by_name)
        if role and role not in roles:
            roles.append(role)
    return ",".join(roles)


def migrate_memberships_and_approval_roles(apps, schema_editor):
    Users = apps.get_model("sql", "Users")
    ResourceGroupMembership = apps.get_model("sql", "ResourceGroupMembership")
    WorkOSDirectoryGroupMembership = apps.get_model(
        "sql", "WorkOSDirectoryGroupMembership"
    )
    Group = apps.get_model("auth", "Group")

    groups_by_id = dict(Group.objects.values_list("id", "name"))
    groups_by_name = {name: name for name in groups_by_id.values()}

    directory_group_ids_by_user = {}
    for membership in WorkOSDirectoryGroupMembership.objects.filter(
        directory_group__is_deleted=False,
        directory_group__resource_group__is_deleted=0,
    ).select_related("directory_group"):
        directory_group_ids_by_user.setdefault(membership.user_id, set()).add(
            membership.directory_group.resource_group_id
        )

    for user in Users.objects.prefetch_related("groups", "resource_group").iterator(
        chunk_size=1000
    ):
        legacy_group_names = [group.name for group in user.groups.all()]
        access_role = _highest_role_for_group_names(legacy_group_names)
        directory_group_ids = directory_group_ids_by_user.get(user.id, set())
        for resource_group in user.resource_group.all():
            membership_source = (
                SOURCE_WORKOS_DIRECTORY
                if resource_group.group_id in directory_group_ids
                else SOURCE_DATAMINGLE
            )
            ResourceGroupMembership.objects.update_or_create(
                user_id=user.id,
                resource_group_id=resource_group.group_id,
                defaults={
                    "access_role": access_role,
                    "membership_source": membership_source,
                },
            )

    for model_name in (
        "WorkflowAuditSetting",
        "SqlWorkflow",
        "QueryPrivilegesApply",
        "PermissionRequest",
        "ArchiveConfig",
    ):
        Model = apps.get_model("sql", model_name)
        for obj in Model.objects.all().iterator():
            normalized = _normalize_approval_sequence(
                obj.audit_auth_groups, groups_by_id, groups_by_name
            )
            if normalized != obj.audit_auth_groups:
                obj.audit_auth_groups = normalized
                obj.save(update_fields=["audit_auth_groups"])

    WorkflowAudit = apps.get_model("sql", "WorkflowAudit")
    for audit in WorkflowAudit.objects.all().iterator():
        update_fields = []
        normalized_groups = _normalize_approval_sequence(
            audit.audit_auth_groups, groups_by_id, groups_by_name
        )
        if normalized_groups != audit.audit_auth_groups:
            audit.audit_auth_groups = normalized_groups
            update_fields.append("audit_auth_groups")
        for field_name in ("current_audit", "next_audit"):
            value = getattr(audit, field_name)
            if str(value).strip() == "-1":
                continue
            normalized = _normalize_approval_token(value, groups_by_id, groups_by_name)
            if normalized and normalized != value:
                setattr(audit, field_name, normalized)
                update_fields.append(field_name)
        if update_fields:
            audit.save(update_fields=update_fields)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0022_infrastructurenode_instance_node_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceGroupMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_role",
                    models.CharField(
                        choices=[
                            ("query", "Query"),
                            ("workflow_requester", "Workflow Requester"),
                            ("workflow_approver", "Workflow Approver"),
                            ("resource_owner", "Resource Owner"),
                        ],
                        db_index=True,
                        default="query",
                        max_length=32,
                        verbose_name="Access Role",
                    ),
                ),
                (
                    "membership_source",
                    models.CharField(
                        choices=[
                            ("datamingle", "Datamingle"),
                            ("workos_directory", "WorkOS Directory"),
                        ],
                        db_index=True,
                        default="datamingle",
                        max_length=32,
                        verbose_name="Membership Source",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("sys_time", models.DateTimeField(auto_now=True)),
                (
                    "resource_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="sql.resourcegroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resource Group Membership",
                "verbose_name_plural": "Resource Group Memberships",
                "db_table": "resource_group_membership",
                "managed": True,
                "indexes": [
                    models.Index(
                        fields=["resource_group", "access_role"],
                        name="rg_membership_group_role_idx",
                    ),
                    models.Index(
                        fields=["user", "access_role"],
                        name="rg_membership_user_role_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "resource_group"),
                        name="resource_group_membership_user_group_uniq",
                    )
                ],
            },
        ),
        migrations.RunPython(migrate_memberships_and_approval_roles, noop_reverse),
    ]
