# Generated by Django 6.0.3 on 2026-06-04 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0023_resourcegroupmembership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructurenode",
            name="address",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=200,
                verbose_name="Node Address",
            ),
        ),
    ]
