# Generated by Django 6.0.3 on 2026-06-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0024_alter_infrastructurenode_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurenode",
            name="monitoring_enabled",
            field=models.BooleanField(default=True, verbose_name="Monitoring Enabled"),
        ),
    ]
