# Generated by Django 6.0.3 on 2026-06-04 19:08

import sql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0025_infrastructurenode_monitoring_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurenode",
            name="monitoring_collectors",
            field=models.JSONField(
                blank=True,
                default=sql.models.default_node_exporter_collectors,
                verbose_name="Monitoring Collectors",
            ),
        ),
    ]
