# Generated by Django 6.0.3 on 2026-06-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0026_infrastructurenode_monitoring_collectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="monitoring_enabled",
            field=models.BooleanField(default=True, verbose_name="Monitoring Enabled"),
        ),
    ]
