# Generated by Django 6.0.3 on 2026-06-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0027_instance_monitoring_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="monitoring_collectors",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Monitoring Collectors",
            ),
        ),
    ]
