# Generated by Django 6.0.3 on 2026-06-04 22:03

from django.db import migrations

DEFAULT_MYSQLD_EXPORTER_COLLECTORS = [
    "global_status",
    "global_variables",
    "slave_status",
]

DEFAULT_POSTGRES_EXPORTER_COLLECTORS = [
    "database",
    "locks",
    "replication",
    "replication_slot",
    "roles",
    "stat_bgwriter",
    "stat_database",
    "stat_progress_vacuum",
    "stat_user_tables",
    "statio_user_tables",
    "wal",
]


def populate_instance_monitoring_collectors(apps, schema_editor):
    instance_model = apps.get_model("sql", "Instance")
    instance_model.objects.filter(
        db_type="mysql", monitoring_collectors__isnull=True
    ).update(monitoring_collectors=DEFAULT_MYSQLD_EXPORTER_COLLECTORS)
    instance_model.objects.filter(db_type="mysql", monitoring_collectors=[]).update(
        monitoring_collectors=DEFAULT_MYSQLD_EXPORTER_COLLECTORS
    )
    instance_model.objects.filter(
        db_type="pgsql", monitoring_collectors__isnull=True
    ).update(monitoring_collectors=DEFAULT_POSTGRES_EXPORTER_COLLECTORS)
    instance_model.objects.filter(db_type="pgsql", monitoring_collectors=[]).update(
        monitoring_collectors=DEFAULT_POSTGRES_EXPORTER_COLLECTORS
    )


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0028_instance_monitoring_collectors"),
    ]

    operations = [
        migrations.RunPython(
            populate_instance_monitoring_collectors,
            migrations.RunPython.noop,
        ),
    ]
