# Generated by Django 6.0.3 on 2026-06-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0029_populate_instance_monitoring_collectors"),
    ]

    operations = [
        migrations.AddField(
            model_name="infrastructurenode",
            name="monitoring_labels",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Monitoring Labels"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="monitoring_labels",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Monitoring Labels"
            ),
        ),
    ]
