# Generated by Django 6.0.3 on 2026-06-11 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sql", "0030_infrastructurenode_monitoring_labels_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ResourceGroup",
            new_name="Team",
        ),
        migrations.RemoveField(
            model_name="workosdirectorygroup",
            name="resource_group",
        ),
        migrations.AlterUniqueTogether(
            name="workosdirectorygroupmembership",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="workosdirectorygroupmembership",
            name="directory_group",
        ),
        migrations.RemoveField(
            model_name="workosdirectorygroupmembership",
            name="user",
        ),
        migrations.DeleteModel(
            name="WorkOSDirectorySyncEvent",
        ),
        migrations.AlterModelOptions(
            name="permanentresourcegroupgrant",
            options={
                "managed": True,
                "verbose_name": "Permanent Team Grant",
                "verbose_name_plural": "Permanent Team Grants",
            },
        ),
        migrations.AlterModelOptions(
            name="permission",
            options={
                "managed": True,
                "permissions": (
                    ("menu_dashboard", "Menu Dashboard"),
                    ("menu_sqlcheck", "Menu SQL Review"),
                    ("menu_sqlworkflow", "Menu SQL Deployment"),
                    ("menu_query", "Menu SQL Query"),
                    ("menu_sqlquery", "Menu Online Query"),
                    ("menu_queryapplylist", "Menu Privilege Management"),
                    ("menu_instance", "Menu Instance Management"),
                    ("menu_instance_list", "Menu Instance List"),
                    ("menu_dbdiagnostic", "Menu Session Management"),
                    ("menu_database", "Menu Database Management"),
                    ("menu_instance_account", "Menu Instance Account Management"),
                    ("menu_param", "Menu Parameter Configuration"),
                    ("menu_data_dictionary", "Menu Data Dictionary"),
                    ("menu_tools", "Menu Tool Plugins"),
                    ("menu_archive", "Menu Data Archive"),
                    ("menu_system", "Menu System Management"),
                    ("menu_openapi", "Menu OpenAPI"),
                    ("sql_submit", "Submit SQL Deployment Workflow"),
                    ("sql_review", "Review SQL Deployment Workflow"),
                    (
                        "sql_execute_for_team",
                        "Execute SQL Deployment Workflow (Team Scope)",
                    ),
                    (
                        "sql_execute",
                        "Execute SQL Deployment Workflow (Own Submissions Only)",
                    ),
                    ("query_applypriv", "Apply Query Privileges"),
                    ("query_mgtpriv", "Manage Query Privileges"),
                    ("query_review", "Review Query Privileges"),
                    ("query_submit", "Submit SQL Query"),
                    ("query_all_instances", "Query All Instances"),
                    ("query_team_instance", "Query All Instances in Team"),
                    ("process_view", "View Sessions"),
                    ("process_kill", "Kill Sessions"),
                    ("tablespace_view", "View Tablespaces"),
                    ("trx_view", "View Transaction Info"),
                    ("trxandlocks_view", "View Lock Info"),
                    ("instance_account_manage", "Manage Instance Accounts"),
                    ("param_view", "View Instance Parameters"),
                    ("param_edit", "Edit Instance Parameters"),
                    ("data_dictionary_export", "Export Data Dictionary"),
                    ("archive_apply", "Submit Archive Request"),
                    ("archive_review", "Review Archive Request"),
                    ("archive_mgt", "Manage Archive Request"),
                    ("audit_user", "Audit Permission"),
                    ("query_download", "Online Query Download Permission"),
                    ("offline_download", "Offline Download Permission"),
                    ("menu_sqlexportworkflow", "Menu Data Export"),
                    ("sqlexport_submit", "Submit Data Export"),
                ),
            },
        ),
        migrations.AlterModelOptions(
            name="resourcegroupmembership",
            options={
                "managed": True,
                "verbose_name": "Team Membership",
                "verbose_name_plural": "Team Memberships",
            },
        ),
        migrations.AlterModelOptions(
            name="team",
            options={
                "managed": True,
                "verbose_name": "Team Management",
                "verbose_name_plural": "Team Management",
            },
        ),
        migrations.AlterModelOptions(
            name="temporaryresourcegroupgrant",
            options={
                "managed": True,
                "verbose_name": "Temporary Team Grant",
                "verbose_name_plural": "Temporary Team Grants",
            },
        ),
        migrations.RenameField(
            model_name="queryprivilegesapply",
            old_name="group_id",
            new_name="team_id",
        ),
        migrations.RenameField(
            model_name="queryprivilegesapply",
            old_name="group_name",
            new_name="team_name",
        ),
        migrations.RenameField(
            model_name="sqlworkflow",
            old_name="group_id",
            new_name="team_id",
        ),
        migrations.RenameField(
            model_name="sqlworkflow",
            old_name="group_name",
            new_name="team_name",
        ),
        migrations.RenameField(
            model_name="workflowaudit",
            old_name="group_id",
            new_name="team_id",
        ),
        migrations.RenameField(
            model_name="workflowaudit",
            old_name="group_name",
            new_name="team_name",
        ),
        migrations.RenameField(
            model_name="workflowauditsetting",
            old_name="group_id",
            new_name="team_id",
        ),
        migrations.RenameField(
            model_name="workflowauditsetting",
            old_name="group_name",
            new_name="team_name",
        ),
        migrations.RemoveField(
            model_name="users",
            name="workos_directory_id",
        ),
        migrations.RemoveField(
            model_name="users",
            name="workos_directory_managed",
        ),
        migrations.RemoveField(
            model_name="users",
            name="workos_directory_user_id",
        ),
        migrations.AddField(
            model_name="permissionrequest",
            name="permission_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permission_requests",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructurenode",
            name="resource_group",
            field=models.ManyToManyField(
                blank=True, to="sql.team", verbose_name="Team"
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="resource_group",
            field=models.ManyToManyField(
                blank=True, to="sql.team", verbose_name="Team"
            ),
        ),
        migrations.AlterField(
            model_name="permissionrequest",
            name="subject_type",
            field=models.CharField(
                choices=[("user", "User"), ("team", "Team")],
                default="user",
                max_length=32,
                verbose_name="Request Subject Type",
            ),
        ),
        migrations.AlterField(
            model_name="permissionrequest",
            name="target_type",
            field=models.CharField(
                choices=[("team", "Team"), ("instance", "Instance")],
                max_length=32,
                verbose_name="Target Type",
            ),
        ),
        migrations.AlterField(
            model_name="resourcegroupmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="workflowauditsetting",
            unique_together={("team_id", "workflow_type")},
        ),
        migrations.DeleteModel(
            name="WorkOSDirectoryGroup",
        ),
        migrations.DeleteModel(
            name="WorkOSDirectoryGroupMembership",
        ),
    ]
