# Generated by Django 6.0.3 on 2026-06-11 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sql", "0031_rename_resource_group_to_team"),
    ]

    operations = [
        migrations.RenameField(
            model_name="archiveconfig",
            old_name="resource_group",
            new_name="team",
        ),
        migrations.RenameField(
            model_name="permissionrequest",
            old_name="resource_group",
            new_name="team",
        ),
        migrations.RenameField(
            model_name="temporaryinstancegrant",
            old_name="resource_group",
            new_name="team",
        ),
        migrations.RemoveField(
            model_name="users",
            name="resource_group",
        ),
        migrations.AddField(
            model_name="permanentresourcegroupgrant",
            name="permission_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permanent_team_grants",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="resourcegroupmembership",
            name="permission_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team_memberships",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="temporaryresourcegroupgrant",
            name="permission_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temporary_team_grants",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="infrastructurenode",
            name="resource_group",
            field=models.ManyToManyField(
                blank=True, to="sql.team", verbose_name="Team"
            ),
        ),
        migrations.AlterField(
            model_name="instance",
            name="resource_group",
            field=models.ManyToManyField(
                blank=True, to="sql.team", verbose_name="Team"
            ),
        ),
    ]
