# Generated by Django 6.0.3 on 2026-06-11 20:54

from django.db import migrations

ROLE_GROUP_NAMES = {
    "query": "QA",
    "workflow_requester": "RD",
    "workflow_approver": "PM",
    "resource_owner": "DBA",
    "team_owner": "DBA",
}


def migrate_team_permission_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    Users = apps.get_model("sql", "Users")
    ResourceGroupMembership = apps.get_model("sql", "ResourceGroupMembership")
    TemporaryResourceGroupGrant = apps.get_model("sql", "TemporaryResourceGroupGrant")
    PermanentResourceGroupGrant = apps.get_model("sql", "PermanentResourceGroupGrant")
    PermissionRequest = apps.get_model("sql", "PermissionRequest")

    groups = {
        name: Group.objects.get_or_create(name=name)[0]
        for name in sorted(set(ROLE_GROUP_NAMES.values()))
    }
    permission_codenames = {
        "QA": {
            "menu_dashboard",
            "menu_sqlcheck",
            "menu_sqlworkflow",
            "menu_query",
            "menu_sqlquery",
            "menu_queryapplylist",
            "menu_data_dictionary",
            "sql_submit",
            "sql_execute",
            "query_applypriv",
            "query_submit",
        },
        "RD": {
            "menu_dashboard",
            "menu_sqlcheck",
            "menu_sqlworkflow",
            "menu_query",
            "menu_sqlquery",
            "menu_queryapplylist",
            "menu_data_dictionary",
            "menu_tools",
            "menu_archive",
            "sql_submit",
            "sql_execute",
            "query_applypriv",
            "query_submit",
            "archive_apply",
        },
        "PM": {
            "menu_dashboard",
            "menu_sqlcheck",
            "menu_sqlworkflow",
            "menu_query",
            "menu_sqlquery",
            "menu_queryapplylist",
            "menu_data_dictionary",
            "menu_tools",
            "menu_archive",
            "sql_submit",
            "sql_review",
            "sql_execute_for_resource_group",
            "sql_execute",
            "query_applypriv",
            "query_review",
            "query_submit",
            "archive_apply",
            "archive_review",
        },
        "DBA": {
            "menu_dashboard",
            "menu_sqlcheck",
            "menu_sqlworkflow",
            "menu_query",
            "menu_sqlquery",
            "menu_queryapplylist",
            "menu_instance",
            "menu_instance_list",
            "menu_dbdiagnostic",
            "menu_database",
            "menu_instance_account",
            "menu_param",
            "menu_data_dictionary",
            "menu_tools",
            "menu_archive",
            "menu_system",
            "menu_openapi",
            "sql_submit",
            "sql_review",
            "sql_execute_for_resource_group",
            "sql_execute",
            "query_applypriv",
            "query_mgtpriv",
            "query_review",
            "query_submit",
            "query_all_instances",
            "query_resource_group_instance",
            "process_view",
            "process_kill",
            "tablespace_view",
            "trx_view",
            "trxandlocks_view",
            "instance_account_manage",
            "param_view",
            "param_edit",
            "data_dictionary_export",
            "archive_apply",
            "archive_review",
            "archive_mgt",
            "change_resourcegroup",
            "view_resourcegroup",
        },
    }
    for group_name, codenames in permission_codenames.items():
        groups[group_name].permissions.add(
            *Permission.objects.filter(codename__in=codenames)
        )

    Users.groups.through.objects.exclude(group__name="superadmin").delete()

    ResourceGroupMembership.objects.filter(
        membership_source="workos_directory"
    ).delete()
    for membership in ResourceGroupMembership.objects.all().iterator():
        group_name = ROLE_GROUP_NAMES.get(membership.access_role, "QA")
        membership.permission_group_id = groups[group_name].id
        membership.save(update_fields=["permission_group"])

    qa_group = groups["QA"]
    PermissionRequest.objects.filter(permission_group__isnull=True).update(
        permission_group=qa_group
    )
    TemporaryResourceGroupGrant.objects.filter(permission_group__isnull=True).update(
        permission_group=qa_group
    )
    PermanentResourceGroupGrant.objects.filter(
        user__isnull=False,
        permission_group__isnull=True,
    ).update(permission_group=qa_group)

    def normalize_group_ids(raw_value):
        normalized = []
        for token in str(raw_value or "").split(","):
            token = token.strip()
            if not token:
                continue
            group_name = ROLE_GROUP_NAMES.get(token)
            if group_name:
                group_id = groups[group_name].id
            elif token.isdigit() and Group.objects.filter(id=int(token)).exists():
                group_id = int(token)
            else:
                group = Group.objects.filter(name=token).first()
                group_id = group.id if group else groups["PM"].id
            if group_id not in normalized:
                normalized.append(group_id)
        return ",".join(str(group_id) for group_id in normalized)

    for model_name in (
        "WorkflowAuditSetting",
        "SqlWorkflow",
        "QueryPrivilegesApply",
        "PermissionRequest",
        "ArchiveConfig",
    ):
        Model = apps.get_model("sql", model_name)
        for obj in Model.objects.all().iterator():
            normalized = normalize_group_ids(obj.audit_auth_groups)
            if normalized != obj.audit_auth_groups:
                obj.audit_auth_groups = normalized
                obj.save(update_fields=["audit_auth_groups"])

    WorkflowAudit = apps.get_model("sql", "WorkflowAudit")
    for audit in WorkflowAudit.objects.all().iterator():
        update_fields = []
        normalized = normalize_group_ids(audit.audit_auth_groups)
        if normalized != audit.audit_auth_groups:
            audit.audit_auth_groups = normalized
            update_fields.append("audit_auth_groups")
        for field_name in ("current_audit", "next_audit"):
            value = getattr(audit, field_name)
            if str(value).strip() == "-1":
                continue
            normalized_value = normalize_group_ids(value)
            if normalized_value and normalized_value != str(value):
                setattr(audit, field_name, normalized_value)
                update_fields.append(field_name)
        if update_fields:
            audit.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0032_prepare_team_permissions"),
    ]

    operations = [
        migrations.RunPython(migrate_team_permission_groups, migrations.RunPython.noop),
    ]
