# Generated by Django 6.0.3 on 2026-06-11 20:58

import django.db.models.deletion
from django.db import migrations, models


def rename_team_permissions(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    team_content_type = ContentType.objects.filter(
        app_label="sql", model="team"
    ).first()
    if team_content_type is None:
        team_content_type = ContentType.objects.filter(
            app_label="sql", model="resourcegroup"
        ).first()
        if team_content_type is not None:
            team_content_type.model = "team"
            team_content_type.save(update_fields=["model"])

    permission_renames = {
        "add_resourcegroup": ("add_team", "Can add team"),
        "change_resourcegroup": ("change_team", "Can change team"),
        "delete_resourcegroup": ("delete_team", "Can delete team"),
        "view_resourcegroup": ("view_team", "Can view team"),
        "sql_execute_for_resource_group": (
            "sql_execute_for_team",
            "Execute SQL for assigned team instances",
        ),
        "query_resource_group_instance": (
            "query_team_instance",
            "Query assigned team instances",
        ),
    }
    queryset = Permission.objects.filter(
        content_type__app_label="sql",
        codename__in=permission_renames,
    )
    for permission in queryset:
        permission.codename, permission.name = permission_renames[permission.codename]
        if team_content_type is not None:
            permission.content_type = team_content_type
        permission.save(update_fields=["codename", "name", "content_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sql", "0033_migrate_team_permission_groups"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="permanentresourcegroupgrant",
            name="permanent_rg_grant_has_user_or_instance",
        ),
        migrations.RemoveIndex(
            model_name="resourcegroupmembership",
            name="rg_membership_group_role_idx",
        ),
        migrations.RemoveIndex(
            model_name="resourcegroupmembership",
            name="rg_membership_user_role_idx",
        ),
        migrations.RemoveConstraint(
            model_name="resourcegroupmembership",
            name="resource_group_membership_user_group_uniq",
        ),
        migrations.RenameModel(
            old_name="PermanentResourceGroupGrant",
            new_name="PermanentTeamGrant",
        ),
        migrations.RenameModel(
            old_name="ResourceGroupMembership",
            new_name="TeamMembership",
        ),
        migrations.RenameModel(
            old_name="TemporaryResourceGroupGrant",
            new_name="TemporaryTeamGrant",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="group_id",
            new_name="team_id",
        ),
        migrations.RenameField(
            model_name="team",
            old_name="group_name",
            new_name="team_name",
        ),
        migrations.RenameField(
            model_name="permanentteamgrant",
            old_name="resource_group",
            new_name="team",
        ),
        migrations.RenameField(
            model_name="teammembership",
            old_name="resource_group",
            new_name="team",
        ),
        migrations.RenameField(
            model_name="temporaryteamgrant",
            old_name="resource_group",
            new_name="team",
        ),
        migrations.RemoveField(
            model_name="teammembership",
            name="access_role",
        ),
        migrations.RemoveField(
            model_name="teammembership",
            name="membership_source",
        ),
        migrations.AlterField(
            model_name="permanentteamgrant",
            name="permission_group",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="permanent_team_grants",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="permission_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="team_memberships",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="temporaryteamgrant",
            name="permission_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="temporary_team_grants",
                to="auth.group",
            ),
        ),
        migrations.AlterModelTable(
            name="permanentteamgrant",
            table="permanent_team_grant",
        ),
        migrations.AlterModelTable(
            name="team",
            table="team",
        ),
        migrations.AlterModelTable(
            name="teammembership",
            table="team_membership",
        ),
        migrations.AlterModelTable(
            name="temporaryteamgrant",
            table="temporary_team_grant",
        ),
        migrations.RunPython(
            rename_team_permissions,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="permanentteamgrant",
            constraint=models.CheckConstraint(
                condition=models.Q(user__isnull=False)
                | models.Q(instance__isnull=False),
                name="permanent_team_grant_has_user_or_instance",
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["team", "permission_group"],
                name="team_membership_team_group_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["user", "permission_group"],
                name="team_membership_user_group_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("user", "team"),
                name="team_membership_user_team_uniq",
            ),
        ),
    ]
