# Generated by Django 6.0.3 on 2026-06-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sql", "0034_rename_team_models"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="teammembership",
            name="team_membership_team_group_idx",
        ),
        migrations.RemoveIndex(
            model_name="teammembership",
            name="team_membership_user_group_idx",
        ),
        migrations.RenameField(
            model_name="permanentteamgrant",
            old_name="permission_group",
            new_name="permission_level",
        ),
        migrations.RenameField(
            model_name="permissionrequest",
            old_name="permission_group",
            new_name="permission_level",
        ),
        migrations.RenameField(
            model_name="teammembership",
            old_name="permission_group",
            new_name="permission_level",
        ),
        migrations.RenameField(
            model_name="temporaryteamgrant",
            old_name="permission_group",
            new_name="permission_level",
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["team", "permission_level"],
                name="team_membership_team_level_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teammembership",
            index=models.Index(
                fields=["user", "permission_level"],
                name="team_membership_user_level_idx",
            ),
        ),
    ]
