# Generated by Django 6.0.3 on 2026-06-13 01:24

from django.db import migrations

TEAM_PERMISSION_CODES = {
    "menu_query",
    "menu_sqlquery",
    "query_submit",
    "query_applypriv",
    "query_review",
    "query_download",
    "menu_sqlcheck",
    "menu_sqlworkflow",
    "sql_submit",
    "sql_review",
    "sql_execute",
    "sql_execute_for_team",
    "menu_sqlexportworkflow",
    "sqlexport_submit",
    "offline_download",
    "menu_archive",
    "archive_apply",
    "archive_review",
    "archive_mgt",
    "view_team",
    "change_team",
}


def restrict_team_permission_levels(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    User = apps.get_model("sql", "Users")
    allowed_ids = set(
        Permission.objects.filter(
            content_type__app_label="sql",
            codename__in=TEAM_PERMISSION_CODES,
        ).values_list("id", flat=True)
    )
    for group in Group.objects.exclude(name="superadmin").iterator():
        disallowed_ids = list(
            group.permissions.exclude(id__in=allowed_ids).values_list("id", flat=True)
        )
        if disallowed_ids:
            group.permissions.remove(*disallowed_ids)
    dba = Group.objects.filter(name="DBA").first()
    if dba:
        dba.permissions.add(
            *Permission.objects.filter(
                content_type__app_label="sql",
                codename__in={"view_team", "change_team"},
            )
        )
    user_groups = User.groups.through
    user_groups.objects.exclude(group__name="superadmin").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0035_remove_teammembership_team_membership_team_group_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(
            restrict_team_permission_levels,
            migrations.RunPython.noop,
        )
    ]
