# Generated by Django 6.0.3 on 2026-06-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0037_backfill_allauth_email_addresses"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="queryable",
            field=models.BooleanField(default=False, verbose_name="Queryable"),
        ),
    ]
