# Generated by Django 6.0.3 on 2026-06-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0038_instance_queryable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instance",
            name="instance_tag",
        ),
        migrations.DeleteModel(
            name="InstanceTag",
        ),
    ]
