# Generated by Django 6.0.3 on 2026-06-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0039_remove_instance_instance_tag_delete_instancetag"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="workflow_enabled",
            field=models.BooleanField(default=False, verbose_name="Workflow Enabled"),
        ),
    ]
