# Generated by Django 6.0.3 on 2026-06-26 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("sql", "0040_instance_workflow_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="sqlworkflow",
            name="workflow_policy_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Workflow Policy Name",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Policy Name"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_workflow_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_workflow_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Policy",
                "verbose_name_plural": "Workflow Policies",
                "db_table": "workflow_policy",
                "ordering": ["name", "id"],
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="instance",
            name="workflow_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sql.workflowpolicy",
                verbose_name="Workflow Policy",
            ),
        ),
        migrations.AddField(
            model_name="sqlworkflow",
            name="workflow_policy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sql.workflowpolicy",
                verbose_name="Workflow Policy",
            ),
        ),
        migrations.CreateModel(
            name="WorkflowPolicyStep",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Order")),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "permission_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflow_policy_steps",
                        to="auth.group",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="sql.workflowpolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workflow Policy Step",
                "verbose_name_plural": "Workflow Policy Steps",
                "db_table": "workflow_policy_step",
                "ordering": ["order", "id"],
                "managed": True,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("policy", "order"),
                        name="workflow_policy_step_policy_order_uniq",
                    )
                ],
            },
        ),
    ]
