# Generated by Django 6.0.3 on 2026-06-26 03:32

from django.db import migrations

SQL_REVIEW_WORKFLOW_TYPE = 2


def _chain_key(raw_value):
    return ",".join(
        value.strip() for value in str(raw_value or "").split(",") if value.strip()
    )


def backfill_workflow_policies(apps, schema_editor):
    WorkflowAuditSetting = apps.get_model("sql", "WorkflowAuditSetting")
    WorkflowPolicy = apps.get_model("sql", "WorkflowPolicy")
    WorkflowPolicyStep = apps.get_model("sql", "WorkflowPolicyStep")
    Instance = apps.get_model("sql", "Instance")

    policy_by_chain = {}
    legacy_settings = WorkflowAuditSetting.objects.filter(
        workflow_type=SQL_REVIEW_WORKFLOW_TYPE
    ).order_by("audit_setting_id")
    for setting in legacy_settings:
        chain = _chain_key(setting.audit_auth_groups)
        if chain in policy_by_chain:
            continue
        suffix = "No approval" if chain == "" else str(len(policy_by_chain) + 1)
        policy = WorkflowPolicy.objects.create(
            name=f"Default SQL Policy {suffix}",
            description="Backfilled from legacy SQL approval settings.",
            is_active=True,
        )
        for index, permission_group_id in enumerate(chain.split(","), start=1):
            if not permission_group_id:
                continue
            WorkflowPolicyStep.objects.create(
                policy=policy,
                order=index,
                permission_group_id=int(permission_group_id),
            )
        policy_by_chain[chain] = policy

    chain_by_team_id = {
        setting.team_id: _chain_key(setting.audit_auth_groups)
        for setting in legacy_settings
    }
    sql_capable_instances = Instance.objects.filter(workflow_enabled=True)
    for instance in sql_capable_instances:
        team_ids = list(
            instance.resource_group.filter(is_deleted=0).values_list(
                "team_id", flat=True
            )
        )
        if not team_ids or any(team_id not in chain_by_team_id for team_id in team_ids):
            continue
        chains = {chain_by_team_id[team_id] for team_id in team_ids}
        if len(chains) != 1:
            continue
        policy = policy_by_chain.get(next(iter(chains)))
        if policy is not None:
            instance.workflow_policy_id = policy.id
            instance.save(update_fields=["workflow_policy"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0041_sqlworkflow_workflow_policy_name_workflowpolicy_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_workflow_policies, noop_reverse),
    ]
