# Generated by Django 6.0.3 on 2026-06-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0042_backfill_workflow_policies"),
    ]

    operations = [
        migrations.AddField(
            model_name="instance",
            name="mysql_cluster_membership_source",
            field=models.CharField(
                choices=[("auto", "Automatic"), ("manual", "Manual")],
                default="auto",
                max_length=16,
                verbose_name="MySQL Cluster Membership Source",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_ddl_dml_block_reason",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="MySQL DDL/DML Block Reason",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_ddl_dml_eligible",
            field=models.BooleanField(
                default=False, verbose_name="MySQL DDL/DML Eligible"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_read_only",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="MySQL Read Only"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_server_uuid",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="MySQL Server UUID"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_source_host",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="MySQL Source Host"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_source_port",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="MySQL Source Port"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_super_read_only",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="MySQL Super Read Only"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_topology_details",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="MySQL Topology Details"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_topology_last_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="MySQL Topology Last Seen At"
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_topology_role",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("standalone", "Standalone"),
                    ("primary", "Primary"),
                    ("replica", "Replica"),
                ],
                default="unknown",
                max_length=16,
                verbose_name="MySQL Topology Role",
            ),
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_topology_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("standalone", "Standalone"),
                    ("clustered", "Clustered"),
                    ("missing_master", "Missing Master"),
                    ("ambiguous_master", "Ambiguous Master"),
                    ("drift", "Topology Drift"),
                ],
                default="unknown",
                max_length=32,
                verbose_name="MySQL Topology Status",
            ),
        ),
        migrations.CreateModel(
            name="MysqlCluster",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Cluster Name")),
                (
                    "label_value",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Cluster Label Value"
                    ),
                ),
                (
                    "cluster_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Cluster Key"
                    ),
                ),
                (
                    "topology_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("ok", "OK"),
                            ("missing_master", "Missing Master"),
                            ("ambiguous_master", "Ambiguous Master"),
                            ("drift", "Topology Drift"),
                        ],
                        default="unknown",
                        max_length=32,
                        verbose_name="Topology Status",
                    ),
                ),
                (
                    "unmanaged_peers",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Unmanaged Peers"
                    ),
                ),
                (
                    "membership_source",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual")],
                        default="auto",
                        max_length=16,
                        verbose_name="Membership Source",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Seen At"
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "primary_instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mysql_primary_clusters",
                        to="sql.instance",
                        verbose_name="Primary Instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "MySQL Cluster",
                "verbose_name_plural": "MySQL Clusters",
                "db_table": "mysql_cluster",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="instance",
            name="mysql_cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instances",
                to="sql.mysqlcluster",
                verbose_name="MySQL Cluster",
            ),
        ),
        migrations.CreateModel(
            name="MysqlTopologyAlert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("drift", "Topology Drift"),
                            ("missing_master", "Missing Master"),
                            ("ambiguous_master", "Ambiguous Master"),
                        ],
                        max_length=32,
                        verbose_name="Alert Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("resolved", "Resolved")],
                        default="active",
                        max_length=16,
                        verbose_name="Alert Status",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="Message")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="sql.mysqlcluster",
                        verbose_name="MySQL Cluster",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mysql_topology_alerts",
                        to="sql.instance",
                        verbose_name="Instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "MySQL Topology Alert",
                "verbose_name_plural": "MySQL Topology Alerts",
                "db_table": "mysql_topology_alert",
                "managed": True,
            },
        ),
        migrations.AddIndex(
            model_name="mysqlcluster",
            index=models.Index(
                fields=["topology_status"], name="mysql_cluster_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mysqltopologyalert",
            index=models.Index(
                fields=["status", "alert_type"], name="mysql_alert_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mysqltopologyalert",
            index=models.Index(
                fields=["cluster", "status"], name="mysql_alert_cluster_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mysqltopologyalert",
            index=models.Index(
                fields=["instance", "status"], name="mysql_alert_instance_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mysqltopologyalert",
            constraint=models.UniqueConstraint(
                fields=("instance", "alert_type", "status"),
                name="mysql_alert_instance_type_status_uniq",
            ),
        ),
    ]
