# Generated by Django 6.0.3 on 2026-07-01 03:55

from django.db import migrations


def backfill_mysql_topology_rollout(apps, schema_editor):
    Instance = apps.get_model("sql", "Instance")
    Instance.objects.filter(
        db_type="mysql",
        type="master",
        workflow_enabled=True,
        mysql_topology_last_seen_at__isnull=True,
        mysql_topology_status="unknown",
    ).update(
        mysql_topology_role="standalone",
        mysql_topology_status="standalone",
        mysql_ddl_dml_eligible=True,
        mysql_ddl_dml_block_reason="",
    )


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0043_instance_mysql_cluster_membership_source_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_mysql_topology_rollout, noop_reverse),
    ]
