# Generated by Django 6.0.3 on 2026-07-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sql", "0044_backfill_mysql_topology_rollout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instance",
            name="db_type",
            field=models.CharField(
                choices=[
                    ("mysql", "MySQL"),
                    ("mssql", "MsSQL"),
                    ("redis", "Redis"),
                    ("pgsql", "PgSQL"),
                    ("oracle", "Oracle"),
                    ("mongo", "Mongo"),
                    ("phoenix", "Phoenix"),
                    ("odps", "ODPS"),
                    ("clickhouse", "ClickHouse"),
                    ("cassandra", "Cassandra"),
                    ("doris", "Doris"),
                    ("elasticsearch", "Elasticsearch"),
                    ("opensearch", "OpenSearch"),
                    ("memcached", "Memcached"),
                ],
                max_length=20,
                verbose_name="Database Type",
            ),
        ),
        migrations.AlterField(
            model_name="paramtemplate",
            name="db_type",
            field=models.CharField(
                choices=[
                    ("mysql", "MySQL"),
                    ("mssql", "MsSQL"),
                    ("redis", "Redis"),
                    ("pgsql", "PgSQL"),
                    ("oracle", "Oracle"),
                    ("mongo", "Mongo"),
                    ("phoenix", "Phoenix"),
                    ("odps", "ODPS"),
                    ("clickhouse", "ClickHouse"),
                    ("cassandra", "Cassandra"),
                    ("doris", "Doris"),
                    ("elasticsearch", "Elasticsearch"),
                    ("opensearch", "OpenSearch"),
                    ("memcached", "Memcached"),
                ],
                max_length=20,
                verbose_name="Database Type",
            ),
        ),
    ]
