# Generated by Django 6.0.3 on 2026-06-06 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricsDashboard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.CharField(db_index=True, max_length=128)),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("time_range_seconds", models.PositiveIntegerField(default=3600)),
                ("refresh_interval_seconds", models.PositiveIntegerField(default=0)),
                ("panels", models.JSONField(blank=True, default=list)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metrics_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "metrics_dashboard",
                "ordering": ("name", "id"),
                "indexes": [
                    models.Index(
                        fields=["organization_id", "name"],
                        name="metrics_dash_org_name_idx",
                    )
                ],
            },
        ),
    ]
