# Generated by Django 6.0.3 on 2026-06-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_metrics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsdashboard",
            name="variables",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
