# Generated by Django 6.0.3 on 2026-06-07 04:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_metrics", "0002_metricsdashboard_variables"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricsDashboardRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("time_range_seconds", models.PositiveIntegerField(default=3600)),
                ("refresh_interval_seconds", models.PositiveIntegerField(default=0)),
                ("variables", models.JSONField(blank=True, default=list)),
                ("panels", models.JSONField(blank=True, default=list)),
                ("saved_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "restored_from_revision",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="api_metrics.metricsdashboard",
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metrics_dashboard_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "metrics_dashboard_revision",
                "ordering": ("-revision",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dashboard", "revision"),
                        name="metrics_dash_revision_unique",
                    )
                ],
            },
        ),
    ]
