# Generated by Django 6.0.3 on 2026-06-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_metrics", "0003_metricsdashboardrevision"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsdashboard",
            name="time_range_end",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="metricsdashboard",
            name="time_range_mode",
            field=models.CharField(default="relative", max_length=16),
        ),
        migrations.AddField(
            model_name="metricsdashboard",
            name="time_range_start",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="metricsdashboardrevision",
            name="time_range_end",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="metricsdashboardrevision",
            name="time_range_mode",
            field=models.CharField(default="relative", max_length=16),
        ),
        migrations.AddField(
            model_name="metricsdashboardrevision",
            name="time_range_start",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
    ]
