# Generated by Django 6.0.3 on 2026-06-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_metrics", "0004_metricsdashboard_time_range_end_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsdashboard",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="dashboard_icons/"
            ),
        ),
    ]
