# Generated by Django 6.0.3 on 2026-06-23 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_metrics", "0006_metricsdashboardfavorite"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="metricsdashboard",
            name="metrics_dash_org_name_idx",
        ),
        migrations.RemoveField(
            model_name="metricsdashboard",
            name="organization_id",
        ),
    ]
