# -*- coding: UTF-8 -*-

from django.urls import path

import sql.instance_database
import sql.query_privileges
from common import config, workflow, check
from common.twofa import totp
from sql import (
    sql_workflow,
    query,
    instance,
    instance_account,
    db_diagnostic,
    resource_group,
    data_dictionary,
    archiver,
    audit_log,
    user,
    offlinedownload,
)
from sql.utils import tasks

urlpatterns = [
    path("downloadfile/", offlinedownload.offline_file_download),
    path("passed/", sql_workflow.passed),
    path("execute/", sql_workflow.execute),
    path("timingtask/", sql_workflow.timing_task),
    path("alter_run_date/", sql_workflow.alter_run_date),
    path("cancel/", sql_workflow.cancel),
    path("sqlworkflow_list/", sql_workflow.sql_workflow_list),
    path("sqlworkflow_list_audit/", sql_workflow.sql_workflow_list_audit),
    path("sqlworkflow/detail_content/", sql_workflow.detail_content),
    path("sqlworkflow/backup_sql/", sql_workflow.backup_sql),
    path("getWorkflowStatus/", sql_workflow.get_workflow_status),
    path("del_sqlcronjob/", tasks.del_schedule),
    path("inception/osc_control/", sql_workflow.osc_control),
    path("workflow/list/", workflow.lists),
    path("workflow/log/", workflow.log),
    path("config/change/", config.change_config),
    path("check/go_inception/", check.go_inception),
    path("check/email/", check.email),
    path("check/instance/", check.instance),
    path("check/file_storage_connect/", check.file_storage_connect),
    path("group/group/", resource_group.group),
    path("group/addrelation/", resource_group.addrelation),
    path("group/relations/", resource_group.associated_objects),
    path("group/instances/", resource_group.instances),
    path("group/unassociated/", resource_group.unassociated_objects),
    path("group/auditors/", resource_group.auditors),
    path("group/changeauditors/", resource_group.changeauditors),
    path("group/user_all_instances/", resource_group.user_all_instances),
    path("instance/list/", instance.lists),
    path("instance/user/list", instance_account.users),
    path("instance/user/create/", instance_account.create),
    path("instance/user/edit/", instance_account.edit),
    path("instance/user/grant/", instance_account.grant),
    path("instance/user/reset_pwd/", instance_account.reset_pwd),
    path("instance/user/lock/", instance_account.lock),
    path("instance/user/delete/", instance_account.delete),
    path("instance/database/list/", sql.instance_database.databases),
    path("instance/database/create/", sql.instance_database.create),
    path("instance/database/edit/", sql.instance_database.edit),
    path("instance/instance_resource/", instance.instance_resource),
    path("instance/describetable/", instance.describe),
    path("data_dictionary/table_list/", data_dictionary.table_list),
    path("data_dictionary/table_info/", data_dictionary.table_info),
    path("data_dictionary/export/", data_dictionary.export),
    path("param/list/", instance.param_list),
    path("param/history/", instance.param_history),
    path("param/edit/", instance.param_edit),
    path("query/", query.query),
    path("query/querylog/", query.querylog),
    path("query/querylog_audit/", query.querylog_audit),
    path("query/favorite/", query.favorite),
    path("query/generate_sql/", query.generate_sql),
    path("check/openai/", query.check_openai),
    path("query/applylist/", sql.query_privileges.query_priv_apply_list),
    path("query/userprivileges/", sql.query_privileges.user_query_priv),
    path("query/applyforprivileges/", sql.query_privileges.query_priv_apply),
    path("query/modifyprivileges/", sql.query_privileges.query_priv_modify),
    path("query/privaudit/", sql.query_privileges.query_priv_audit),
    path("db_diagnostic/process/", db_diagnostic.process),
    path("db_diagnostic/create_kill_session/", db_diagnostic.create_kill_session),
    path("db_diagnostic/kill_session/", db_diagnostic.kill_session),
    path("db_diagnostic/tablespace/", db_diagnostic.tablespace),
    path("db_diagnostic/trxandlocks/", db_diagnostic.trxandlocks),
    path("db_diagnostic/innodb_trx/", db_diagnostic.innodb_trx),
    path("archive/list/", archiver.archive_list),
    path("archive/apply/", archiver.archive_apply),
    path("archive/audit/", archiver.archive_audit),
    path("archive/switch/", archiver.archive_switch),
    path("archive/once/", archiver.archive_once),
    path("archive/log/", archiver.archive_log),
    path("audit/log/", audit_log.audit_log),
    path("audit/input/", audit_log.audit_input),
    path("user/list/", user.lists),
    path("user/qrcode/<str:data>/", totp.generate_qrcode),
]
