name: Publish Docker image

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  push_to_registries:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            hhyo/archery
            ghcr.io/${{ github.repository }}

      - name: Build Docker base image
        run: docker build -f src/docker/Dockerfile-base -t archery-base:ci .

      - name: Build Docker images
        env:
          DOCKER_TAGS: ${{ steps.meta.outputs.tags }}
          DOCKER_LABELS: ${{ steps.meta.outputs.labels }}
        run: |
          readarray -t tags <<< "$DOCKER_TAGS"
          readarray -t labels <<< "$DOCKER_LABELS"

          tag_args=()
          for tag in "${tags[@]}"; do
            if [ -n "$tag" ]; then
              tag_args+=("-t" "$tag")
            fi
          done

          label_args=()
          for label in "${labels[@]}"; do
            if [ -n "$label" ]; then
              label_args+=("--label" "$label")
            fi
          done

          docker build \
            --build-arg BASE_IMAGE=archery-base:ci \
            "${tag_args[@]}" \
            "${label_args[@]}" \
            -f src/docker/Dockerfile \
            .

      - name: Push Docker images
        if: github.event_name != 'pull_request'
        env:
          DOCKER_TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          readarray -t tags <<< "$DOCKER_TAGS"
          for tag in "${tags[@]}"; do
            if [ -n "$tag" ]; then
              docker push "$tag"
            fi
          done
